/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/areainsights/v1/area_insights_service.proto

// Protobuf Java Version: 3.25.8
package com.google.maps.areainsights.v1;

public final class AreaInsightsServiceProto {
  private AreaInsightsServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_ComputeInsightsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_ComputeInsightsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_ComputeInsightsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_ComputeInsightsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_PlaceInsight_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_PlaceInsight_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_Filter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_Filter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_LocationFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_LocationFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_LocationFilter_Circle_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_LocationFilter_Circle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_LocationFilter_Region_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_LocationFilter_Region_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_Polygon_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_Polygon_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_TypeFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_TypeFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_maps_areainsights_v1_RatingFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_maps_areainsights_v1_RatingFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "7google/maps/areainsights/v1/area_insights_service.proto\022\033google.maps.areainsig"
          + "hts.v1\032\034google/api/annotations.proto\032\027go"
          + "ogle/api/client.proto\032\037google/api/field_"
          + "behavior.proto\032\031google/api/resource.proto\032\030google/type/latlng.proto\"\217\001\n"
          + "\026ComputeInsightsRequest\022;\n"
          + "\010insights\030\004"
          + " \003(\0162$.google.maps.areainsights.v1.InsightB\003\340A\002\0228\n"
          + "\006filter\030\005 \001(\0132#.google.maps.areainsights.v1.FilterB\003\340A\002\"z\n"
          + "\027ComputeInsightsResponse\022\022\n"
          + "\005count\030\001 \001(\003H\000\210\001\001\022A\n"
          + "\016place_insights\030\005 \003(\0132).google.maps.areainsights.v1.PlaceInsightB\010\n"
          + "\006_count\"?\n"
          + "\014PlaceInsight\022/\n"
          + "\005place\030\001 \001(\tB \372A\035\n"
          + "\033places.googleapis.com/Place\"\356\002\n"
          + "\006Filter\022I\n"
          + "\017location_filter\030\001 \001(\0132+"
          + ".google.maps.areainsights.v1.LocationFilterB\003\340A\002\022A\n"
          + "\013type_filter\030\002"
          + " \001(\0132\'.google.maps.areainsights.v1.TypeFilterB\003\340A\002\022K\n"
          + "\020operating_status\030\003"
          + " \003(\0162,.google.maps.areainsights.v1.OperatingStatusB\003\340A\001\022B\n"
          + "\014price_levels\030\004"
          + " \003(\0162\'.google.maps.areainsights.v1.PriceLevelB\003\340A\001\022E\n\r"
          + "rating_filter\030\005 "
          + "\001(\0132).google.maps.areainsights.v1.RatingFilterB\003\340A\001\"\336\004\n"
          + "\016LocationFilter\022D\n"
          + "\006circle\030\001"
          + " \001(\01322.google.maps.areainsights.v1.LocationFilter.CircleH\000\022D\n"
          + "\006region\030\002 \001(\01322.g"
          + "oogle.maps.areainsights.v1.LocationFilter.RegionH\000\022M\n"
          + "\013custom_area\030\003 \001(\01326.google"
          + ".maps.areainsights.v1.LocationFilter.CustomAreaH\000\032\202\001\n"
          + "\006Circle\022&\n"
          + "\007lat_lng\030\001 \001(\0132\023.google.type.LatLngH\000\0221\n"
          + "\005place\030\002 \001(\tB \372A\035\n"
          + "\033places.googleapis.com/PlaceH\000\022\023\n"
          + "\006radius\030\003 \001(\005B\003\340A\001B\010\n"
          + "\006center\032E\n"
          + "\006Region\0221\n"
          + "\005place\030\001 \001(\tB \372A\035\n"
          + "\033places.googleapis.com/PlaceH\000B\010\n"
          + "\006region\032\234\001\n\n"
          + "CustomArea\022T\n"
          + "\007polygon\030\001"
          + " \001(\0132>.google.maps.areainsights.v1.LocationFilter.CustomArea.PolygonB\003\340A\002\0328\n"
          + "\007Polygon\022-\n"
          + "\013coordinates\030\001 \003(\0132\023.google.type.LatLngB\003\340A\001B\006\n"
          + "\004area\"\220\001\n\n"
          + "TypeFilter\022\033\n"
          + "\016included_types\030\001 \003(\tB\003\340A\001\022\033\n"
          + "\016excluded_types\030\002 \003(\tB\003\340A\001\022#\n"
          + "\026included_primary_types\030\003 \003(\tB\003\340A\001\022#\n"
          + "\026excluded_primary_types\030\004 \003(\tB\003\340A\001\"h\n"
          + "\014RatingFilter\022\034\n\n"
          + "min_rating\030\005 \001(\002B\003\340A\001H\000\210\001\001\022\034\n\n"
          + "max_rating\030\006 \001(\002B\003\340A\001H\001\210\001\001B\r\n"
          + "\013_min_ratingB\r\n"
          + "\013_max_rating*I\n"
          + "\007Insight\022\027\n"
          + "\023INSIGHT_UNSPECIFIED\020\000\022\021\n\r"
          + "INSIGHT_COUNT\020\001\022\022\n"
          + "\016INSIGHT_PLACES\020\002*\247\001\n"
          + "\017OperatingStatus\022 \n"
          + "\034OPERATING_STATUS_UNSPECIFIED\020\000\022 \n"
          + "\034OPERATING_STATUS_OPERATIONAL\020\001\022\'\n"
          + "#OPERATING_STATUS_PERMANENTLY_CLOSED\020\003\022\'\n"
          + "#OPERATING_STATUS_TEMPORARILY_CLOSED\020\004*\261\001\n\n"
          + "PriceLevel\022\033\n"
          + "\027PRICE_LEVEL_UNSPECIFIED\020\000\022\024\n"
          + "\020PRICE_LEVEL_FREE\020\001\022\033\n"
          + "\027PRICE_LEVEL_INEXPENSIVE\020\002\022\030\n"
          + "\024PRICE_LEVEL_MODERATE\020\003\022\031\n"
          + "\025PRICE_LEVEL_EXPENSIVE\020\004\022\036\n"
          + "\032PRICE_LEVEL_VERY_EXPENSIVE\020\0052\376\001\n"
          + "\014AreaInsights\022\234\001\n"
          + "\017ComputeInsights\0223.google.maps.areainsigh"
          + "ts.v1.ComputeInsightsRequest\0324.google.maps.areainsights.v1.ComputeInsightsRespon"
          + "se\"\036\202\323\344\223\002\030\"\023/v1:computeInsights:\001*\032O\312A\033a"
          + "reainsights.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\375\001\n"
          + "\037com.google.maps.areainsights.v1B\030AreaIns"
          + "ightsServiceProtoP\001ZIcloud.google.com/go/maps/areainsights/apiv1/areainsightspb;"
          + "areainsightspb\242\002\003MAI\252\002\033Google.Maps.AreaI"
          + "nsights.V1\312\002\033Google\\Maps\\AreaInsights\\V1\352A0\n"
          + "\033places.googleapis.com/Place\022\021places/{place_id}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.type.LatLngProto.getDescriptor(),
            });
    internal_static_google_maps_areainsights_v1_ComputeInsightsRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_maps_areainsights_v1_ComputeInsightsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_ComputeInsightsRequest_descriptor,
            new java.lang.String[] {
              "Insights", "Filter",
            });
    internal_static_google_maps_areainsights_v1_ComputeInsightsResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_maps_areainsights_v1_ComputeInsightsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_ComputeInsightsResponse_descriptor,
            new java.lang.String[] {
              "Count", "PlaceInsights",
            });
    internal_static_google_maps_areainsights_v1_PlaceInsight_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_maps_areainsights_v1_PlaceInsight_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_PlaceInsight_descriptor,
            new java.lang.String[] {
              "Place",
            });
    internal_static_google_maps_areainsights_v1_Filter_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_maps_areainsights_v1_Filter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_Filter_descriptor,
            new java.lang.String[] {
              "LocationFilter", "TypeFilter", "OperatingStatus", "PriceLevels", "RatingFilter",
            });
    internal_static_google_maps_areainsights_v1_LocationFilter_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_maps_areainsights_v1_LocationFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_LocationFilter_descriptor,
            new java.lang.String[] {
              "Circle", "Region", "CustomArea", "Area",
            });
    internal_static_google_maps_areainsights_v1_LocationFilter_Circle_descriptor =
        internal_static_google_maps_areainsights_v1_LocationFilter_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_maps_areainsights_v1_LocationFilter_Circle_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_LocationFilter_Circle_descriptor,
            new java.lang.String[] {
              "LatLng", "Place", "Radius", "Center",
            });
    internal_static_google_maps_areainsights_v1_LocationFilter_Region_descriptor =
        internal_static_google_maps_areainsights_v1_LocationFilter_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_maps_areainsights_v1_LocationFilter_Region_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_LocationFilter_Region_descriptor,
            new java.lang.String[] {
              "Place", "Region",
            });
    internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_descriptor =
        internal_static_google_maps_areainsights_v1_LocationFilter_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_descriptor,
            new java.lang.String[] {
              "Polygon",
            });
    internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_Polygon_descriptor =
        internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_Polygon_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_LocationFilter_CustomArea_Polygon_descriptor,
            new java.lang.String[] {
              "Coordinates",
            });
    internal_static_google_maps_areainsights_v1_TypeFilter_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_maps_areainsights_v1_TypeFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_TypeFilter_descriptor,
            new java.lang.String[] {
              "IncludedTypes", "ExcludedTypes", "IncludedPrimaryTypes", "ExcludedPrimaryTypes",
            });
    internal_static_google_maps_areainsights_v1_RatingFilter_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_maps_areainsights_v1_RatingFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_maps_areainsights_v1_RatingFilter_descriptor,
            new java.lang.String[] {
              "MinRating", "MaxRating",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.type.LatLngProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
