# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api-name: analyticsdata
deep-copy-regex:
  - dest: /owl-bot-staging/java-analytics-data/$1/proto-google-analytics-data-$1/src
    source: /google/analytics/data/(v.*)/.*-java/proto-google-.*/src
  - dest: /owl-bot-staging/java-analytics-data/$1/grpc-google-analytics-data-$1/src
    source: /google/analytics/data/(v.*)/.*-java/grpc-google-.*/src
  - dest: /owl-bot-staging/java-analytics-data/$1/google-analytics-data/src
    source: /google/analytics/data/(v.*)/.*-java/gapic-google-.*/src
deep-preserve-regex:
  - /java-analytics-data/google-.*/src/main/resources/META-INF/native-image/*
  - /java-analytics-data/google-.*/src/test/resources/META-INF/native-image/*
deep-remove-regex:
  - /java-analytics-data/grpc-google-.*/src
  - /java-analytics-data/proto-google-.*/src
  - /java-analytics-data/google-.*/src
