// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/iot/v1/device_manager.proto

package com.google.cloud.iot.v1;

/**
 * <pre>
 * Request for `ListDevices`.
 * </pre>
 *
 * Protobuf type {@code google.cloud.iot.v1.ListDevicesRequest}
 */
public  final class ListDevicesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.cloud.iot.v1.ListDevicesRequest)
    ListDevicesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListDevicesRequest.newBuilder() to construct.
  private ListDevicesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListDevicesRequest() {
    parent_ = "";
    deviceNumIds_ = java.util.Collections.emptyList();
    deviceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    pageSize_ = 0;
    pageToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListDevicesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            parent_ = s;
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              deviceNumIds_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000002;
            }
            deviceNumIds_.add(input.readUInt64());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              deviceNumIds_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              deviceNumIds_.add(input.readUInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              deviceIds_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            deviceIds_.add(s);
            break;
          }
          case 34: {
            com.google.protobuf.FieldMask.Builder subBuilder = null;
            if (fieldMask_ != null) {
              subBuilder = fieldMask_.toBuilder();
            }
            fieldMask_ = input.readMessage(com.google.protobuf.FieldMask.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fieldMask_);
              fieldMask_ = subBuilder.buildPartial();
            }

            break;
          }
          case 800: {

            pageSize_ = input.readInt32();
            break;
          }
          case 810: {
            java.lang.String s = input.readStringRequireUtf8();

            pageToken_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        deviceNumIds_ = java.util.Collections.unmodifiableList(deviceNumIds_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        deviceIds_ = deviceIds_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.iot.v1.DeviceManagerProto.internal_static_google_cloud_iot_v1_ListDevicesRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.iot.v1.DeviceManagerProto.internal_static_google_cloud_iot_v1_ListDevicesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.iot.v1.ListDevicesRequest.class, com.google.cloud.iot.v1.ListDevicesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object parent_;
  /**
   * <pre>
   * The device registry path. Required. For example,
   * `projects/my-project/locations/us-central1/registries/my-registry`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  public java.lang.String getParent() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The device registry path. Required. For example,
   * `projects/my-project/locations/us-central1/registries/my-registry`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  public com.google.protobuf.ByteString
      getParentBytes() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_NUM_IDS_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Long> deviceNumIds_;
  /**
   * <pre>
   * A list of device numerical ids. If empty, it will ignore this field. This
   * field cannot hold more than 10,000 entries.
   * </pre>
   *
   * <code>repeated uint64 device_num_ids = 2;</code>
   */
  public java.util.List<java.lang.Long>
      getDeviceNumIdsList() {
    return deviceNumIds_;
  }
  /**
   * <pre>
   * A list of device numerical ids. If empty, it will ignore this field. This
   * field cannot hold more than 10,000 entries.
   * </pre>
   *
   * <code>repeated uint64 device_num_ids = 2;</code>
   */
  public int getDeviceNumIdsCount() {
    return deviceNumIds_.size();
  }
  /**
   * <pre>
   * A list of device numerical ids. If empty, it will ignore this field. This
   * field cannot hold more than 10,000 entries.
   * </pre>
   *
   * <code>repeated uint64 device_num_ids = 2;</code>
   */
  public long getDeviceNumIds(int index) {
    return deviceNumIds_.get(index);
  }
  private int deviceNumIdsMemoizedSerializedSize = -1;

  public static final int DEVICE_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList deviceIds_;
  /**
   * <pre>
   * A list of device string identifiers. If empty, it will ignore this field.
   * For example, `['device0', 'device12']`. This field cannot hold more than
   * 10,000 entries.
   * </pre>
   *
   * <code>repeated string device_ids = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getDeviceIdsList() {
    return deviceIds_;
  }
  /**
   * <pre>
   * A list of device string identifiers. If empty, it will ignore this field.
   * For example, `['device0', 'device12']`. This field cannot hold more than
   * 10,000 entries.
   * </pre>
   *
   * <code>repeated string device_ids = 3;</code>
   */
  public int getDeviceIdsCount() {
    return deviceIds_.size();
  }
  /**
   * <pre>
   * A list of device string identifiers. If empty, it will ignore this field.
   * For example, `['device0', 'device12']`. This field cannot hold more than
   * 10,000 entries.
   * </pre>
   *
   * <code>repeated string device_ids = 3;</code>
   */
  public java.lang.String getDeviceIds(int index) {
    return deviceIds_.get(index);
  }
  /**
   * <pre>
   * A list of device string identifiers. If empty, it will ignore this field.
   * For example, `['device0', 'device12']`. This field cannot hold more than
   * 10,000 entries.
   * </pre>
   *
   * <code>repeated string device_ids = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceIdsBytes(int index) {
    return deviceIds_.getByteString(index);
  }

  public static final int FIELD_MASK_FIELD_NUMBER = 4;
  private com.google.protobuf.FieldMask fieldMask_;
  /**
   * <pre>
   * The fields of the `Device` resource to be returned in the response. The
   * fields `id`, and `num_id` are always returned by default, along with any
   * other fields specified.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   */
  public boolean hasFieldMask() {
    return fieldMask_ != null;
  }
  /**
   * <pre>
   * The fields of the `Device` resource to be returned in the response. The
   * fields `id`, and `num_id` are always returned by default, along with any
   * other fields specified.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   */
  public com.google.protobuf.FieldMask getFieldMask() {
    return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
  }
  /**
   * <pre>
   * The fields of the `Device` resource to be returned in the response. The
   * fields `id`, and `num_id` are always returned by default, along with any
   * other fields specified.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask field_mask = 4;</code>
   */
  public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
    return getFieldMask();
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 100;
  private int pageSize_;
  /**
   * <pre>
   * The maximum number of devices to return in the response. If this value
   * is zero, the service will select a default size. A call may return fewer
   * objects than requested, but if there is a non-empty `page_token`, it
   * indicates that more entries are available.
   * </pre>
   *
   * <code>int32 page_size = 100;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int PAGE_TOKEN_FIELD_NUMBER = 101;
  private volatile java.lang.Object pageToken_;
  /**
   * <pre>
   * The value returned by the last `ListDevicesResponse`; indicates
   * that this is a continuation of a prior `ListDevices` call, and
   * that the system should return the next page of data.
   * </pre>
   *
   * <code>string page_token = 101;</code>
   */
  public java.lang.String getPageToken() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The value returned by the last `ListDevicesResponse`; indicates
   * that this is a continuation of a prior `ListDevices` call, and
   * that the system should return the next page of data.
   * </pre>
   *
   * <code>string page_token = 101;</code>
   */
  public com.google.protobuf.ByteString
      getPageTokenBytes() {
    java.lang.Object ref = pageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getParentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, parent_);
    }
    if (getDeviceNumIdsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(deviceNumIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < deviceNumIds_.size(); i++) {
      output.writeUInt64NoTag(deviceNumIds_.get(i));
    }
    for (int i = 0; i < deviceIds_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, deviceIds_.getRaw(i));
    }
    if (fieldMask_ != null) {
      output.writeMessage(4, getFieldMask());
    }
    if (pageSize_ != 0) {
      output.writeInt32(100, pageSize_);
    }
    if (!getPageTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 101, pageToken_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getParentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, parent_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < deviceNumIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeUInt64SizeNoTag(deviceNumIds_.get(i));
      }
      size += dataSize;
      if (!getDeviceNumIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      deviceNumIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < deviceIds_.size(); i++) {
        dataSize += computeStringSizeNoTag(deviceIds_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDeviceIdsList().size();
    }
    if (fieldMask_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFieldMask());
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(100, pageSize_);
    }
    if (!getPageTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, pageToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.iot.v1.ListDevicesRequest)) {
      return super.equals(obj);
    }
    com.google.cloud.iot.v1.ListDevicesRequest other = (com.google.cloud.iot.v1.ListDevicesRequest) obj;

    boolean result = true;
    result = result && getParent()
        .equals(other.getParent());
    result = result && getDeviceNumIdsList()
        .equals(other.getDeviceNumIdsList());
    result = result && getDeviceIdsList()
        .equals(other.getDeviceIdsList());
    result = result && (hasFieldMask() == other.hasFieldMask());
    if (hasFieldMask()) {
      result = result && getFieldMask()
          .equals(other.getFieldMask());
    }
    result = result && (getPageSize()
        == other.getPageSize());
    result = result && getPageToken()
        .equals(other.getPageToken());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent().hashCode();
    if (getDeviceNumIdsCount() > 0) {
      hash = (37 * hash) + DEVICE_NUM_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceNumIdsList().hashCode();
    }
    if (getDeviceIdsCount() > 0) {
      hash = (37 * hash) + DEVICE_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceIdsList().hashCode();
    }
    if (hasFieldMask()) {
      hash = (37 * hash) + FIELD_MASK_FIELD_NUMBER;
      hash = (53 * hash) + getFieldMask().hashCode();
    }
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getPageToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.iot.v1.ListDevicesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.iot.v1.ListDevicesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request for `ListDevices`.
   * </pre>
   *
   * Protobuf type {@code google.cloud.iot.v1.ListDevicesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.cloud.iot.v1.ListDevicesRequest)
      com.google.cloud.iot.v1.ListDevicesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.iot.v1.DeviceManagerProto.internal_static_google_cloud_iot_v1_ListDevicesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.iot.v1.DeviceManagerProto.internal_static_google_cloud_iot_v1_ListDevicesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.iot.v1.ListDevicesRequest.class, com.google.cloud.iot.v1.ListDevicesRequest.Builder.class);
    }

    // Construct using com.google.cloud.iot.v1.ListDevicesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      parent_ = "";

      deviceNumIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      deviceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = null;
      } else {
        fieldMask_ = null;
        fieldMaskBuilder_ = null;
      }
      pageSize_ = 0;

      pageToken_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.iot.v1.DeviceManagerProto.internal_static_google_cloud_iot_v1_ListDevicesRequest_descriptor;
    }

    public com.google.cloud.iot.v1.ListDevicesRequest getDefaultInstanceForType() {
      return com.google.cloud.iot.v1.ListDevicesRequest.getDefaultInstance();
    }

    public com.google.cloud.iot.v1.ListDevicesRequest build() {
      com.google.cloud.iot.v1.ListDevicesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.cloud.iot.v1.ListDevicesRequest buildPartial() {
      com.google.cloud.iot.v1.ListDevicesRequest result = new com.google.cloud.iot.v1.ListDevicesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.parent_ = parent_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        deviceNumIds_ = java.util.Collections.unmodifiableList(deviceNumIds_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.deviceNumIds_ = deviceNumIds_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        deviceIds_ = deviceIds_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.deviceIds_ = deviceIds_;
      if (fieldMaskBuilder_ == null) {
        result.fieldMask_ = fieldMask_;
      } else {
        result.fieldMask_ = fieldMaskBuilder_.build();
      }
      result.pageSize_ = pageSize_;
      result.pageToken_ = pageToken_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.iot.v1.ListDevicesRequest) {
        return mergeFrom((com.google.cloud.iot.v1.ListDevicesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.iot.v1.ListDevicesRequest other) {
      if (other == com.google.cloud.iot.v1.ListDevicesRequest.getDefaultInstance()) return this;
      if (!other.getParent().isEmpty()) {
        parent_ = other.parent_;
        onChanged();
      }
      if (!other.deviceNumIds_.isEmpty()) {
        if (deviceNumIds_.isEmpty()) {
          deviceNumIds_ = other.deviceNumIds_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDeviceNumIdsIsMutable();
          deviceNumIds_.addAll(other.deviceNumIds_);
        }
        onChanged();
      }
      if (!other.deviceIds_.isEmpty()) {
        if (deviceIds_.isEmpty()) {
          deviceIds_ = other.deviceIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDeviceIdsIsMutable();
          deviceIds_.addAll(other.deviceIds_);
        }
        onChanged();
      }
      if (other.hasFieldMask()) {
        mergeFieldMask(other.getFieldMask());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (!other.getPageToken().isEmpty()) {
        pageToken_ = other.pageToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.iot.v1.ListDevicesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.iot.v1.ListDevicesRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object parent_ = "";
    /**
     * <pre>
     * The device registry path. Required. For example,
     * `projects/my-project/locations/us-central1/registries/my-registry`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public java.lang.String getParent() {
      java.lang.Object ref = parent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The device registry path. Required. For example,
     * `projects/my-project/locations/us-central1/registries/my-registry`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParentBytes() {
      java.lang.Object ref = parent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The device registry path. Required. For example,
     * `projects/my-project/locations/us-central1/registries/my-registry`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder setParent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The device registry path. Required. For example,
     * `projects/my-project/locations/us-central1/registries/my-registry`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder clearParent() {
      
      parent_ = getDefaultInstance().getParent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The device registry path. Required. For example,
     * `projects/my-project/locations/us-central1/registries/my-registry`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder setParentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parent_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Long> deviceNumIds_ = java.util.Collections.emptyList();
    private void ensureDeviceNumIdsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        deviceNumIds_ = new java.util.ArrayList<java.lang.Long>(deviceNumIds_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public java.util.List<java.lang.Long>
        getDeviceNumIdsList() {
      return java.util.Collections.unmodifiableList(deviceNumIds_);
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public int getDeviceNumIdsCount() {
      return deviceNumIds_.size();
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public long getDeviceNumIds(int index) {
      return deviceNumIds_.get(index);
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public Builder setDeviceNumIds(
        int index, long value) {
      ensureDeviceNumIdsIsMutable();
      deviceNumIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public Builder addDeviceNumIds(long value) {
      ensureDeviceNumIdsIsMutable();
      deviceNumIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public Builder addAllDeviceNumIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureDeviceNumIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, deviceNumIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device numerical ids. If empty, it will ignore this field. This
     * field cannot hold more than 10,000 entries.
     * </pre>
     *
     * <code>repeated uint64 device_num_ids = 2;</code>
     */
    public Builder clearDeviceNumIds() {
      deviceNumIds_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList deviceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureDeviceIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        deviceIds_ = new com.google.protobuf.LazyStringArrayList(deviceIds_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDeviceIdsList() {
      return deviceIds_.getUnmodifiableView();
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public int getDeviceIdsCount() {
      return deviceIds_.size();
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public java.lang.String getDeviceIds(int index) {
      return deviceIds_.get(index);
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdsBytes(int index) {
      return deviceIds_.getByteString(index);
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public Builder setDeviceIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDeviceIdsIsMutable();
      deviceIds_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public Builder addDeviceIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureDeviceIdsIsMutable();
      deviceIds_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public Builder addAllDeviceIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureDeviceIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, deviceIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public Builder clearDeviceIds() {
      deviceIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A list of device string identifiers. If empty, it will ignore this field.
     * For example, `['device0', 'device12']`. This field cannot hold more than
     * 10,000 entries.
     * </pre>
     *
     * <code>repeated string device_ids = 3;</code>
     */
    public Builder addDeviceIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureDeviceIdsIsMutable();
      deviceIds_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.FieldMask fieldMask_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> fieldMaskBuilder_;
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public boolean hasFieldMask() {
      return fieldMaskBuilder_ != null || fieldMask_ != null;
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public com.google.protobuf.FieldMask getFieldMask() {
      if (fieldMaskBuilder_ == null) {
        return fieldMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      } else {
        return fieldMaskBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public Builder setFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fieldMask_ = value;
        onChanged();
      } else {
        fieldMaskBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public Builder setFieldMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = builderForValue.build();
        onChanged();
      } else {
        fieldMaskBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public Builder mergeFieldMask(com.google.protobuf.FieldMask value) {
      if (fieldMaskBuilder_ == null) {
        if (fieldMask_ != null) {
          fieldMask_ =
            com.google.protobuf.FieldMask.newBuilder(fieldMask_).mergeFrom(value).buildPartial();
        } else {
          fieldMask_ = value;
        }
        onChanged();
      } else {
        fieldMaskBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public Builder clearFieldMask() {
      if (fieldMaskBuilder_ == null) {
        fieldMask_ = null;
        onChanged();
      } else {
        fieldMask_ = null;
        fieldMaskBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public com.google.protobuf.FieldMask.Builder getFieldMaskBuilder() {
      
      onChanged();
      return getFieldMaskFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    public com.google.protobuf.FieldMaskOrBuilder getFieldMaskOrBuilder() {
      if (fieldMaskBuilder_ != null) {
        return fieldMaskBuilder_.getMessageOrBuilder();
      } else {
        return fieldMask_ == null ?
            com.google.protobuf.FieldMask.getDefaultInstance() : fieldMask_;
      }
    }
    /**
     * <pre>
     * The fields of the `Device` resource to be returned in the response. The
     * fields `id`, and `num_id` are always returned by default, along with any
     * other fields specified.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask field_mask = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder> 
        getFieldMaskFieldBuilder() {
      if (fieldMaskBuilder_ == null) {
        fieldMaskBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.FieldMask, com.google.protobuf.FieldMask.Builder, com.google.protobuf.FieldMaskOrBuilder>(
                getFieldMask(),
                getParentForChildren(),
                isClean());
        fieldMask_ = null;
      }
      return fieldMaskBuilder_;
    }

    private int pageSize_ ;
    /**
     * <pre>
     * The maximum number of devices to return in the response. If this value
     * is zero, the service will select a default size. A call may return fewer
     * objects than requested, but if there is a non-empty `page_token`, it
     * indicates that more entries are available.
     * </pre>
     *
     * <code>int32 page_size = 100;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <pre>
     * The maximum number of devices to return in the response. If this value
     * is zero, the service will select a default size. A call may return fewer
     * objects than requested, but if there is a non-empty `page_token`, it
     * indicates that more entries are available.
     * </pre>
     *
     * <code>int32 page_size = 100;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The maximum number of devices to return in the response. If this value
     * is zero, the service will select a default size. A call may return fewer
     * objects than requested, but if there is a non-empty `page_token`, it
     * indicates that more entries are available.
     * </pre>
     *
     * <code>int32 page_size = 100;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object pageToken_ = "";
    /**
     * <pre>
     * The value returned by the last `ListDevicesResponse`; indicates
     * that this is a continuation of a prior `ListDevices` call, and
     * that the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 101;</code>
     */
    public java.lang.String getPageToken() {
      java.lang.Object ref = pageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The value returned by the last `ListDevicesResponse`; indicates
     * that this is a continuation of a prior `ListDevices` call, and
     * that the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 101;</code>
     */
    public com.google.protobuf.ByteString
        getPageTokenBytes() {
      java.lang.Object ref = pageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The value returned by the last `ListDevicesResponse`; indicates
     * that this is a continuation of a prior `ListDevices` call, and
     * that the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 101;</code>
     */
    public Builder setPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The value returned by the last `ListDevicesResponse`; indicates
     * that this is a continuation of a prior `ListDevices` call, and
     * that the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 101;</code>
     */
    public Builder clearPageToken() {
      
      pageToken_ = getDefaultInstance().getPageToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The value returned by the last `ListDevicesResponse`; indicates
     * that this is a continuation of a prior `ListDevices` call, and
     * that the system should return the next page of data.
     * </pre>
     *
     * <code>string page_token = 101;</code>
     */
    public Builder setPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pageToken_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.cloud.iot.v1.ListDevicesRequest)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.iot.v1.ListDevicesRequest)
  private static final com.google.cloud.iot.v1.ListDevicesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.iot.v1.ListDevicesRequest();
  }

  public static com.google.cloud.iot.v1.ListDevicesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListDevicesRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListDevicesRequest>() {
    public ListDevicesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListDevicesRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListDevicesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListDevicesRequest> getParserForType() {
    return PARSER;
  }

  public com.google.cloud.iot.v1.ListDevicesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

