branches:
  - branch: 1.127.12-sp
    bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.3.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.10.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.19.x
bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
