primaryBranch: main
releaseType: java-yoshi
manifest: true
handleGHRelease: true
branches:
  - branch: 1.0.x
    releaseType: java-backport
    bumpMinorPreMajor: true
    handleGHRelease: true
  - branch: 1.13.x
    releaseType: java-backport
    manifest: true
    handleGHRelease: true
  - branch: 1.25.x
    releaseType: java-backport
    manifest: true
    handleGHRelease: true
  - branch: 1.37.x
    releaseType: java-backport
    manifest: true
    handleGHRelease: true
  - branch: 1.50.x
    releaseType: java-backport
    manifest: true
    handleGHRelease: true
