bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
    - branch: java7
    - branch: 3.7.x
      releaseType: java-backport
    - branch: 3.13.x
      releaseType: java-backport
    - branch: 3.17.x
      releaseType: java-backport
    - branch: 3.21.x
      releaseType: java-backport
    - branch: 3.22.x
      releaseType: java-backport
    - branch: protobuf-4.x-rc
      manifest: true
extraFiles:
    - >-
      google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java
