deep-remove-regex:
- /java-firestore/grpc-google-.*/src
- /java-firestore/proto-google-.*/src
- /java-firestore/google-cloud-firestore/src/.*/java/com/google/cloud/firestore/v1/
- /java-firestore/google-cloud-firestore-admin/src
deep-preserve-regex:
- /java-firestore/.*google-.*/src/main/java/.*/stub/(Version|FirestoreAdminVersion).java
- /java-firestore/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java
- /java-firestore/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentPathName.java
- /java-firestore/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/AnyPathName.java
- /java-firestore/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DatabaseRootName.java
- /java-firestore/proto-google-cloud-firestore-v1/src/main/java/com/google/firestore/v1/DocumentRootName.java
- /java-firestore/proto-google-cloud-firestore-admin-v1/src/main/java/com/google/firestore/admin/v1/ParentName.java
- /java-firestore/proto-google-cloud-firestore-v1/src/main/proto/firestore
deep-copy-regex:
- source: /google/firestore/(v\d)/.*-java/proto-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/proto-google-cloud-firestore-$1/src
- source: /google/firestore/(v\d)/.*-java/grpc-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/grpc-google-cloud-firestore-$1/src
- source: /google/firestore/(v\d)/.*-java/gapic-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/google-cloud-firestore/src
- source: /google/firestore/admin/(v\d)/.*-java/proto-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/proto-google-cloud-firestore-admin-$1/src
- source: /google/firestore/admin/(v\d)/.*-java/grpc-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/grpc-google-cloud-firestore-admin-$1/src
- source: /google/firestore/admin/(v\d)/.*-java/gapic-google-.*/src
  dest: /owl-bot-staging/java-firestore/$1/google-cloud-firestore-admin/src
- source: /google/firestore/bundle/.*-java/proto-google-.*/src
  dest: /owl-bot-staging/java-firestore/v1/proto-google-cloud-firestore-bundle-v1/src
