/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/aiplatform/v1beta1/vizier_service.proto

// Protobuf Java Version: 3.25.2
package com.google.cloud.aiplatform.v1beta1;

public final class VizierServiceProto {
  private VizierServiceProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_GetStudyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_GetStudyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CreateStudyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CreateStudyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListStudiesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListStudiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListStudiesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListStudiesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_DeleteStudyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_DeleteStudyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_LookupStudyRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_LookupStudyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CreateTrialRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CreateTrialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_GetTrialRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_GetTrialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListTrialsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListTrialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListTrialsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListTrialsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_AddTrialMeasurementRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_AddTrialMeasurementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CompleteTrialRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CompleteTrialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_DeleteTrialRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_DeleteTrialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateMetatdata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateMetatdata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_StopTrialRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_StopTrialRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n4google/cloud/aiplatform/v1beta1/vizier"
          + "_service.proto\022\037google.cloud.aiplatform."
          + "v1beta1\032\034google/api/annotations.proto\032\027g"
          + "oogle/api/client.proto\032\037google/api/field"
          + "_behavior.proto\032\031google/api/resource.pro"
          + "to\032/google/cloud/aiplatform/v1beta1/oper"
          + "ation.proto\032+google/cloud/aiplatform/v1b"
          + "eta1/study.proto\032#google/longrunning/ope"
          + "rations.proto\032\033google/protobuf/empty.pro"
          + "to\032\037google/protobuf/timestamp.proto\"I\n\017G"
          + "etStudyRequest\0226\n\004name\030\001 \001(\tB(\342A\001\002\372A!\n\037a"
          + "iplatform.googleapis.com/Study\"\215\001\n\022Creat"
          + "eStudyRequest\022:\n\006parent\030\001 \001(\tB*\342A\001\002\372A#\n!"
          + "locations.googleapis.com/Location\022;\n\005stu"
          + "dy\030\002 \001(\0132&.google.cloud.aiplatform.v1bet"
          + "a1.StudyB\004\342A\001\002\"\203\001\n\022ListStudiesRequest\022:\n"
          + "\006parent\030\001 \001(\tB*\342A\001\002\372A#\n!locations.google"
          + "apis.com/Location\022\030\n\npage_token\030\002 \001(\tB\004\342"
          + "A\001\001\022\027\n\tpage_size\030\003 \001(\005B\004\342A\001\001\"g\n\023ListStud"
          + "iesResponse\0227\n\007studies\030\001 \003(\0132&.google.cl"
          + "oud.aiplatform.v1beta1.Study\022\027\n\017next_pag"
          + "e_token\030\002 \001(\t\"L\n\022DeleteStudyRequest\0226\n\004n"
          + "ame\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplatform.googleapi"
          + "s.com/Study\"l\n\022LookupStudyRequest\022:\n\006par"
          + "ent\030\001 \001(\tB*\342A\001\002\372A#\n!locations.googleapis"
          + ".com/Location\022\032\n\014display_name\030\002 \001(\tB\004\342A\001"
          + "\002\"\320\001\n\024SuggestTrialsRequest\0228\n\006parent\030\001 \001"
          + "(\tB(\342A\001\002\372A!\n\037aiplatform.googleapis.com/S"
          + "tudy\022\036\n\020suggestion_count\030\002 \001(\005B\004\342A\001\002\022\027\n\t"
          + "client_id\030\003 \001(\tB\004\342A\001\002\022E\n\010contexts\030\004 \003(\0132"
          + "-.google.cloud.aiplatform.v1beta1.TrialC"
          + "ontextB\004\342A\001\001\"\360\001\n\025SuggestTrialsResponse\0226"
          + "\n\006trials\030\001 \003(\0132&.google.cloud.aiplatform"
          + ".v1beta1.Trial\022A\n\013study_state\030\002 \001(\0162,.go"
          + "ogle.cloud.aiplatform.v1beta1.Study.Stat"
          + "e\022.\n\nstart_time\030\003 \001(\0132\032.google.protobuf."
          + "Timestamp\022,\n\010end_time\030\004 \001(\0132\032.google.pro"
          + "tobuf.Timestamp\"\177\n\025SuggestTrialsMetadata"
          + "\022S\n\020generic_metadata\030\001 \001(\01329.google.clou"
          + "d.aiplatform.v1beta1.GenericOperationMet"
          + "adata\022\021\n\tclient_id\030\002 \001(\t\"\213\001\n\022CreateTrial"
          + "Request\0228\n\006parent\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplat"
          + "form.googleapis.com/Study\022;\n\005trial\030\002 \001(\013"
          + "2&.google.cloud.aiplatform.v1beta1.Trial"
          + "B\004\342A\001\002\"I\n\017GetTrialRequest\0226\n\004name\030\001 \001(\tB"
          + "(\342A\001\002\372A!\n\037aiplatform.googleapis.com/Tria"
          + "l\"\200\001\n\021ListTrialsRequest\0228\n\006parent\030\001 \001(\tB"
          + "(\342A\001\002\372A!\n\037aiplatform.googleapis.com/Stud"
          + "y\022\030\n\npage_token\030\002 \001(\tB\004\342A\001\001\022\027\n\tpage_size"
          + "\030\003 \001(\005B\004\342A\001\001\"e\n\022ListTrialsResponse\0226\n\006tr"
          + "ials\030\001 \003(\0132&.google.cloud.aiplatform.v1b"
          + "eta1.Trial\022\027\n\017next_page_token\030\002 \001(\t\"\243\001\n\032"
          + "AddTrialMeasurementRequest\022<\n\ntrial_name"
          + "\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplatform.googleapis.c"
          + "om/Trial\022G\n\013measurement\030\003 \001(\0132,.google.c"
          + "loud.aiplatform.v1beta1.MeasurementB\004\342A\001"
          + "\002\"\336\001\n\024CompleteTrialRequest\0226\n\004name\030\001 \001(\t"
          + "B(\342A\001\002\372A!\n\037aiplatform.googleapis.com/Tri"
          + "al\022M\n\021final_measurement\030\002 \001(\0132,.google.c"
          + "loud.aiplatform.v1beta1.MeasurementB\004\342A\001"
          + "\001\022\036\n\020trial_infeasible\030\003 \001(\010B\004\342A\001\001\022\037\n\021inf"
          + "easible_reason\030\004 \001(\tB\004\342A\001\001\"L\n\022DeleteTria"
          + "lRequest\0226\n\004name\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplatf"
          + "orm.googleapis.com/Trial\"c\n#CheckTrialEa"
          + "rlyStoppingStateRequest\022<\n\ntrial_name\030\001 "
          + "\001(\tB(\342A\001\002\372A!\n\037aiplatform.googleapis.com/"
          + "Trial\";\n$CheckTrialEarlyStoppingStateRes"
          + "ponse\022\023\n\013should_stop\030\001 \001(\010\"\232\001\n%CheckTria"
          + "lEarlyStoppingStateMetatdata\022S\n\020generic_"
          + "metadata\030\001 \001(\01329.google.cloud.aiplatform"
          + ".v1beta1.GenericOperationMetadata\022\r\n\005stu"
          + "dy\030\002 \001(\t\022\r\n\005trial\030\003 \001(\t\"J\n\020StopTrialRequ"
          + "est\0226\n\004name\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplatform.g"
          + "oogleapis.com/Trial\"T\n\030ListOptimalTrials"
          + "Request\0228\n\006parent\030\001 \001(\tB(\342A\001\002\372A!\n\037aiplat"
          + "form.googleapis.com/Study\"[\n\031ListOptimal"
          + "TrialsResponse\022>\n\016optimal_trials\030\001 \003(\0132&"
          + ".google.cloud.aiplatform.v1beta1.Trial2\241"
          + "\030\n\rVizierService\022\272\001\n\013CreateStudy\0223.googl"
          + "e.cloud.aiplatform.v1beta1.CreateStudyRe"
          + "quest\032&.google.cloud.aiplatform.v1beta1."
          + "Study\"N\332A\014parent,study\202\323\344\223\0029\"0/v1beta1/{"
          + "parent=projects/*/locations/*}/studies:\005"
          + "study\022\245\001\n\010GetStudy\0220.google.cloud.aiplat"
          + "form.v1beta1.GetStudyRequest\032&.google.cl"
          + "oud.aiplatform.v1beta1.Study\"?\332A\004name\202\323\344"
          + "\223\0022\0220/v1beta1/{name=projects/*/locations"
          + "/*/studies/*}\022\273\001\n\013ListStudies\0223.google.c"
          + "loud.aiplatform.v1beta1.ListStudiesReque"
          + "st\0324.google.cloud.aiplatform.v1beta1.Lis"
          + "tStudiesResponse\"A\332A\006parent\202\323\344\223\0022\0220/v1be"
          + "ta1/{parent=projects/*/locations/*}/stud"
          + "ies\022\233\001\n\013DeleteStudy\0223.google.cloud.aipla"
          + "tform.v1beta1.DeleteStudyRequest\032\026.googl"
          + "e.protobuf.Empty\"?\332A\004name\202\323\344\223\0022*0/v1beta"
          + "1/{name=projects/*/locations/*/studies/*"
          + "}\022\267\001\n\013LookupStudy\0223.google.cloud.aiplatf"
          + "orm.v1beta1.LookupStudyRequest\032&.google."
          + "cloud.aiplatform.v1beta1.Study\"K\332A\006paren"
          + "t\202\323\344\223\002<\"7/v1beta1/{parent=projects/*/loc"
          + "ations/*}/studies:lookup:\001*\022\344\001\n\rSuggestT"
          + "rials\0225.google.cloud.aiplatform.v1beta1."
          + "SuggestTrialsRequest\032\035.google.longrunnin"
          + "g.Operation\"}\312A.\n\025SuggestTrialsResponse\022"
          + "\025SuggestTrialsMetadata\202\323\344\223\002F\"A/v1beta1/{"
          + "parent=projects/*/locations/*/studies/*}"
          + "/trials:suggest:\001*\022\303\001\n\013CreateTrial\0223.goo"
          + "gle.cloud.aiplatform.v1beta1.CreateTrial"
          + "Request\032&.google.cloud.aiplatform.v1beta"
          + "1.Trial\"W\332A\014parent,trial\202\323\344\223\002B\"9/v1beta1"
          + "/{parent=projects/*/locations/*/studies/"
          + "*}/trials:\005trial\022\256\001\n\010GetTrial\0220.google.c"
          + "loud.aiplatform.v1beta1.GetTrialRequest\032"
          + "&.google.cloud.aiplatform.v1beta1.Trial\""
          + "H\332A\004name\202\323\344\223\002;\0229/v1beta1/{name=projects/"
          + "*/locations/*/studies/*/trials/*}\022\301\001\n\nLi"
          + "stTrials\0222.google.cloud.aiplatform.v1bet"
          + "a1.ListTrialsRequest\0323.google.cloud.aipl"
          + "atform.v1beta1.ListTrialsResponse\"J\332A\006pa"
          + "rent\202\323\344\223\002;\0229/v1beta1/{parent=projects/*/"
          + "locations/*/studies/*}/trials\022\332\001\n\023AddTri"
          + "alMeasurement\022;.google.cloud.aiplatform."
          + "v1beta1.AddTrialMeasurementRequest\032&.goo"
          + "gle.cloud.aiplatform.v1beta1.Trial\"^\202\323\344\223"
          + "\002X\"S/v1beta1/{trial_name=projects/*/loca"
          + "tions/*/studies/*/trials/*}:addTrialMeas"
          + "urement:\001*\022\275\001\n\rCompleteTrial\0225.google.cl"
          + "oud.aiplatform.v1beta1.CompleteTrialRequ"
          + "est\032&.google.cloud.aiplatform.v1beta1.Tr"
          + "ial\"M\202\323\344\223\002G\"B/v1beta1/{name=projects/*/l"
          + "ocations/*/studies/*/trials/*}:complete:"
          + "\001*\022\244\001\n\013DeleteTrial\0223.google.cloud.aiplat"
          + "form.v1beta1.DeleteTrialRequest\032\026.google"
          + ".protobuf.Empty\"H\332A\004name\202\323\344\223\002;*9/v1beta1"
          + "/{name=projects/*/locations/*/studies/*/"
          + "trials/*}\022\275\002\n\034CheckTrialEarlyStoppingSta"
          + "te\022D.google.cloud.aiplatform.v1beta1.Che"
          + "ckTrialEarlyStoppingStateRequest\032\035.googl"
          + "e.longrunning.Operation\"\267\001\312AM\n$CheckTria"
          + "lEarlyStoppingStateResponse\022%CheckTrialE"
          + "arlyStoppingStateMetatdata\202\323\344\223\002a\"\\/v1bet"
          + "a1/{trial_name=projects/*/locations/*/st"
          + "udies/*/trials/*}:checkTrialEarlyStoppin"
          + "gState:\001*\022\261\001\n\tStopTrial\0221.google.cloud.a"
          + "iplatform.v1beta1.StopTrialRequest\032&.goo"
          + "gle.cloud.aiplatform.v1beta1.Trial\"I\202\323\344\223"
          + "\002C\">/v1beta1/{name=projects/*/locations/"
          + "*/studies/*/trials/*}:stop:\001*\022\353\001\n\021ListOp"
          + "timalTrials\0229.google.cloud.aiplatform.v1"
          + "beta1.ListOptimalTrialsRequest\032:.google."
          + "cloud.aiplatform.v1beta1.ListOptimalTria"
          + "lsResponse\"_\332A\006parent\202\323\344\223\002P\"K/v1beta1/{p"
          + "arent=projects/*/locations/*/studies/*}/"
          + "trials:listOptimalTrials:\001*\032M\312A\031aiplatfo"
          + "rm.googleapis.com\322A.https://www.googleap"
          + "is.com/auth/cloud-platformB\351\001\n#com.googl"
          + "e.cloud.aiplatform.v1beta1B\022VizierServic"
          + "eProtoP\001ZCcloud.google.com/go/aiplatform"
          + "/apiv1beta1/aiplatformpb;aiplatformpb\252\002\037"
          + "Google.Cloud.AIPlatform.V1Beta1\312\002\037Google"
          + "\\Cloud\\AIPlatform\\V1beta1\352\002\"Google::Clou"
          + "d::AIPlatform::V1beta1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.aiplatform.v1beta1.OperationProto.getDescriptor(),
              com.google.cloud.aiplatform.v1beta1.StudyProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_aiplatform_v1beta1_GetStudyRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_aiplatform_v1beta1_GetStudyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_GetStudyRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CreateStudyRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_aiplatform_v1beta1_CreateStudyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CreateStudyRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Study",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListStudiesRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_aiplatform_v1beta1_ListStudiesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListStudiesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageToken", "PageSize",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListStudiesResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_aiplatform_v1beta1_ListStudiesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListStudiesResponse_descriptor,
            new java.lang.String[] {
              "Studies", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1beta1_DeleteStudyRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_aiplatform_v1beta1_DeleteStudyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_DeleteStudyRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1beta1_LookupStudyRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_aiplatform_v1beta1_LookupStudyRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_LookupStudyRequest_descriptor,
            new java.lang.String[] {
              "Parent", "DisplayName",
            });
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "SuggestionCount", "ClientId", "Contexts",
            });
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsResponse_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsResponse_descriptor,
            new java.lang.String[] {
              "Trials", "StudyState", "StartTime", "EndTime",
            });
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsMetadata_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_SuggestTrialsMetadata_descriptor,
            new java.lang.String[] {
              "GenericMetadata", "ClientId",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CreateTrialRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_aiplatform_v1beta1_CreateTrialRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CreateTrialRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Trial",
            });
    internal_static_google_cloud_aiplatform_v1beta1_GetTrialRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_aiplatform_v1beta1_GetTrialRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_GetTrialRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListTrialsRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_aiplatform_v1beta1_ListTrialsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListTrialsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageToken", "PageSize",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListTrialsResponse_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_aiplatform_v1beta1_ListTrialsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListTrialsResponse_descriptor,
            new java.lang.String[] {
              "Trials", "NextPageToken",
            });
    internal_static_google_cloud_aiplatform_v1beta1_AddTrialMeasurementRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_aiplatform_v1beta1_AddTrialMeasurementRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_AddTrialMeasurementRequest_descriptor,
            new java.lang.String[] {
              "TrialName", "Measurement",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CompleteTrialRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_aiplatform_v1beta1_CompleteTrialRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CompleteTrialRequest_descriptor,
            new java.lang.String[] {
              "Name", "FinalMeasurement", "TrialInfeasible", "InfeasibleReason",
            });
    internal_static_google_cloud_aiplatform_v1beta1_DeleteTrialRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_aiplatform_v1beta1_DeleteTrialRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_DeleteTrialRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateRequest_descriptor,
            new java.lang.String[] {
              "TrialName",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateResponse_descriptor,
            new java.lang.String[] {
              "ShouldStop",
            });
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateMetatdata_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateMetatdata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_CheckTrialEarlyStoppingStateMetatdata_descriptor,
            new java.lang.String[] {
              "GenericMetadata", "Study", "Trial",
            });
    internal_static_google_cloud_aiplatform_v1beta1_StopTrialRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_aiplatform_v1beta1_StopTrialRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_StopTrialRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsRequest_descriptor,
            new java.lang.String[] {
              "Parent",
            });
    internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsResponse_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_aiplatform_v1beta1_ListOptimalTrialsResponse_descriptor,
            new java.lang.String[] {
              "OptimalTrials",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.OperationProto.getDescriptor();
    com.google.cloud.aiplatform.v1beta1.StudyProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
