# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/samples/snippets/generated"
- "/grpc-google-.*/src"
- "/proto-google-.*/src"
- "/google-.*/src"

deep-preserve-regex:
- "/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/proto-google-cloud-scheduler-v1/src/main/java/com/google/cloud/scheduler/v1/ProjectName.java"
- "/proto-google-cloud-scheduler-v1beta1/src/main/java/com/google/cloud/scheduler/v1beta1/ProjectName.java"

deep-copy-regex:
- source: "/google/cloud/scheduler/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-scheduler/$1/proto-google-cloud-scheduler-$1/src"
- source: "/google/cloud/scheduler/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-scheduler/$1/grpc-google-cloud-scheduler-$1/src"
- source: "/google/cloud/scheduler/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-scheduler/$1/google-cloud-scheduler/src"
- source: "/google/cloud/scheduler/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-scheduler/$1/samples/snippets/generated"

api-name: cloudscheduler
