# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/java-video-stitcher/grpc-google-.*/src"
- "/java-video-stitcher/proto-google-.*/src"
- "/java-video-stitcher/google-.*/src"

deep-preserve-regex:
- "/java-video-stitcher/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"

deep-copy-regex:
- source: "/google/cloud/video/stitcher/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-video-stitcher/$1/proto-google-cloud-video-stitcher-$1/src"
- source: "/google/cloud/video/stitcher/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-video-stitcher/$1/grpc-google-cloud-video-stitcher-$1/src"
- source: "/google/cloud/video/stitcher/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-video-stitcher/$1/google-cloud-video-stitcher/src"

api-name: videostitcher
