/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/maps/fleetengine/v1/trip_api.proto

package google.maps.fleetengine.v1;

/**
 *
 *
 * <pre>
 * GetTrip request message.
 * </pre>
 *
 * Protobuf type {@code maps.fleetengine.v1.GetTripRequest}
 */
public final class GetTripRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:maps.fleetengine.v1.GetTripRequest)
    GetTripRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use GetTripRequest.newBuilder() to construct.
  private GetTripRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private GetTripRequest() {
    name_ = "";
    view_ = 0;
    routeFormatType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new GetTripRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return google.maps.fleetengine.v1.TripApi
        .internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return google.maps.fleetengine.v1.TripApi
        .internal_static_maps_fleetengine_v1_GetTripRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            google.maps.fleetengine.v1.GetTripRequest.class,
            google.maps.fleetengine.v1.GetTripRequest.Builder.class);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private google.maps.fleetengine.v1.RequestHeader header_;
  /**
   *
   *
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   *
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   *
   *
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   *
   * @return The header.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeader getHeader() {
    return header_ == null
        ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()
        : header_;
  }
  /**
   *
   *
   * <pre>
   * The standard Fleet Engine request header.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null
        ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()
        : header_;
  }

  public static final int NAME_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   *
   *
   * <pre>
   * Required. Must be in the format `providers/{provider}/trips/{trip}`.
   * The provider must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>
   * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. Must be in the format `providers/{provider}/trips/{trip}`.
   * The provider must be the Project ID (for example, `sample-cloud-project`)
   * of the Google Cloud Project of which the service account making
   * this call is a member.
   * </pre>
   *
   * <code>
   * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VIEW_FIELD_NUMBER = 11;
  private int view_ = 0;
  /**
   *
   *
   * <pre>
   * The subset of Trip fields that should be returned and their interpretation.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TripView view = 11;</code>
   *
   * @return The enum numeric value on the wire for view.
   */
  @java.lang.Override
  public int getViewValue() {
    return view_;
  }
  /**
   *
   *
   * <pre>
   * The subset of Trip fields that should be returned and their interpretation.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.TripView view = 11;</code>
   *
   * @return The view.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.TripView getView() {
    google.maps.fleetengine.v1.TripView result =
        google.maps.fleetengine.v1.TripView.forNumber(view_);
    return result == null ? google.maps.fleetengine.v1.TripView.UNRECOGNIZED : result;
  }

  public static final int CURRENT_ROUTE_SEGMENT_VERSION_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp currentRouteSegmentVersion_;
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   *
   * @return Whether the currentRouteSegmentVersion field is set.
   */
  @java.lang.Override
  public boolean hasCurrentRouteSegmentVersion() {
    return currentRouteSegmentVersion_ != null;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   *
   * @return The currentRouteSegmentVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCurrentRouteSegmentVersion() {
    return currentRouteSegmentVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : currentRouteSegmentVersion_;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
   * `Trip.current_route_segment` data are retrieved. If route data are
   * unchanged since this timestamp, the route field is not set in the response.
   * If a minimum is unspecified, the route data are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentVersionOrBuilder() {
    return currentRouteSegmentVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : currentRouteSegmentVersion_;
  }

  public static final int REMAINING_WAYPOINTS_VERSION_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp remainingWaypointsVersion_;
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   *
   * @return Whether the remainingWaypointsVersion field is set.
   */
  @java.lang.Override
  public boolean hasRemainingWaypointsVersion() {
    return remainingWaypointsVersion_ != null;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   *
   * @return The remainingWaypointsVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRemainingWaypointsVersion() {
    return remainingWaypointsVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : remainingWaypointsVersion_;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
   * timestamp, the `remaining_waypoints` are not set in the response. If this
   * field is unspecified, `remaining_waypoints` is always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsVersionOrBuilder() {
    return remainingWaypointsVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : remainingWaypointsVersion_;
  }

  public static final int ROUTE_FORMAT_TYPE_FIELD_NUMBER = 8;
  private int routeFormatType_ = 0;
  /**
   *
   *
   * <pre>
   * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
   * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
   * is `LAT_LNG_LIST_TYPE`.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
   *
   * @return The enum numeric value on the wire for routeFormatType.
   */
  @java.lang.Override
  public int getRouteFormatTypeValue() {
    return routeFormatType_;
  }
  /**
   *
   *
   * <pre>
   * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
   * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
   * is `LAT_LNG_LIST_TYPE`.
   * </pre>
   *
   * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
   *
   * @return The routeFormatType.
   */
  @java.lang.Override
  public google.maps.fleetengine.v1.PolylineFormatType getRouteFormatType() {
    google.maps.fleetengine.v1.PolylineFormatType result =
        google.maps.fleetengine.v1.PolylineFormatType.forNumber(routeFormatType_);
    return result == null ? google.maps.fleetengine.v1.PolylineFormatType.UNRECOGNIZED : result;
  }

  public static final int CURRENT_ROUTE_SEGMENT_TRAFFIC_VERSION_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp currentRouteSegmentTrafficVersion_;
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   *
   * @return Whether the currentRouteSegmentTrafficVersion field is set.
   */
  @java.lang.Override
  public boolean hasCurrentRouteSegmentTrafficVersion() {
    return currentRouteSegmentTrafficVersion_ != null;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   *
   * @return The currentRouteSegmentTrafficVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCurrentRouteSegmentTrafficVersion() {
    return currentRouteSegmentTrafficVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : currentRouteSegmentTrafficVersion_;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
   * unchanged since this timestamp, the `current_route_segment_traffic` field
   * is not set in the response. If a minimum is unspecified, the traffic data
   * are always retrieved. Note that traffic is only available for On-Demand
   * Rides and Deliveries Solution customers.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentTrafficVersionOrBuilder() {
    return currentRouteSegmentTrafficVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : currentRouteSegmentTrafficVersion_;
  }

  public static final int REMAINING_WAYPOINTS_ROUTE_VERSION_FIELD_NUMBER = 10;
  private com.google.protobuf.Timestamp remainingWaypointsRouteVersion_;
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   *
   * @return Whether the remainingWaypointsRouteVersion field is set.
   */
  @java.lang.Override
  public boolean hasRemainingWaypointsRouteVersion() {
    return remainingWaypointsRouteVersion_ != null;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   *
   * @return The remainingWaypointsRouteVersion.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRemainingWaypointsRouteVersion() {
    return remainingWaypointsRouteVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : remainingWaypointsRouteVersion_;
  }
  /**
   *
   *
   * <pre>
   * Indicates the minimum timestamp (exclusive) for which
   * `Trip.remaining_waypoints.traffic_to_waypoint` and
   * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
   * unchanged since this timestamp, the fields above are
   * not set in the response. If `remaining_waypoints_route_version` is
   * unspecified, traffic and path are always retrieved.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsRouteVersionOrBuilder() {
    return remainingWaypointsRouteVersion_ == null
        ? com.google.protobuf.Timestamp.getDefaultInstance()
        : remainingWaypointsRouteVersion_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (currentRouteSegmentVersion_ != null) {
      output.writeMessage(6, getCurrentRouteSegmentVersion());
    }
    if (remainingWaypointsVersion_ != null) {
      output.writeMessage(7, getRemainingWaypointsVersion());
    }
    if (routeFormatType_
        != google.maps.fleetengine.v1.PolylineFormatType.UNKNOWN_FORMAT_TYPE.getNumber()) {
      output.writeEnum(8, routeFormatType_);
    }
    if (currentRouteSegmentTrafficVersion_ != null) {
      output.writeMessage(9, getCurrentRouteSegmentTrafficVersion());
    }
    if (remainingWaypointsRouteVersion_ != null) {
      output.writeMessage(10, getRemainingWaypointsRouteVersion());
    }
    if (view_ != google.maps.fleetengine.v1.TripView.TRIP_VIEW_UNSPECIFIED.getNumber()) {
      output.writeEnum(11, view_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getHeader());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (currentRouteSegmentVersion_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              6, getCurrentRouteSegmentVersion());
    }
    if (remainingWaypointsVersion_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              7, getRemainingWaypointsVersion());
    }
    if (routeFormatType_
        != google.maps.fleetengine.v1.PolylineFormatType.UNKNOWN_FORMAT_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(8, routeFormatType_);
    }
    if (currentRouteSegmentTrafficVersion_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              9, getCurrentRouteSegmentTrafficVersion());
    }
    if (remainingWaypointsRouteVersion_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              10, getRemainingWaypointsRouteVersion());
    }
    if (view_ != google.maps.fleetengine.v1.TripView.TRIP_VIEW_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(11, view_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof google.maps.fleetengine.v1.GetTripRequest)) {
      return super.equals(obj);
    }
    google.maps.fleetengine.v1.GetTripRequest other =
        (google.maps.fleetengine.v1.GetTripRequest) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader().equals(other.getHeader())) return false;
    }
    if (!getName().equals(other.getName())) return false;
    if (view_ != other.view_) return false;
    if (hasCurrentRouteSegmentVersion() != other.hasCurrentRouteSegmentVersion()) return false;
    if (hasCurrentRouteSegmentVersion()) {
      if (!getCurrentRouteSegmentVersion().equals(other.getCurrentRouteSegmentVersion()))
        return false;
    }
    if (hasRemainingWaypointsVersion() != other.hasRemainingWaypointsVersion()) return false;
    if (hasRemainingWaypointsVersion()) {
      if (!getRemainingWaypointsVersion().equals(other.getRemainingWaypointsVersion()))
        return false;
    }
    if (routeFormatType_ != other.routeFormatType_) return false;
    if (hasCurrentRouteSegmentTrafficVersion() != other.hasCurrentRouteSegmentTrafficVersion())
      return false;
    if (hasCurrentRouteSegmentTrafficVersion()) {
      if (!getCurrentRouteSegmentTrafficVersion()
          .equals(other.getCurrentRouteSegmentTrafficVersion())) return false;
    }
    if (hasRemainingWaypointsRouteVersion() != other.hasRemainingWaypointsRouteVersion())
      return false;
    if (hasRemainingWaypointsRouteVersion()) {
      if (!getRemainingWaypointsRouteVersion().equals(other.getRemainingWaypointsRouteVersion()))
        return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + VIEW_FIELD_NUMBER;
    hash = (53 * hash) + view_;
    if (hasCurrentRouteSegmentVersion()) {
      hash = (37 * hash) + CURRENT_ROUTE_SEGMENT_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRouteSegmentVersion().hashCode();
    }
    if (hasRemainingWaypointsVersion()) {
      hash = (37 * hash) + REMAINING_WAYPOINTS_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getRemainingWaypointsVersion().hashCode();
    }
    hash = (37 * hash) + ROUTE_FORMAT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + routeFormatType_;
    if (hasCurrentRouteSegmentTrafficVersion()) {
      hash = (37 * hash) + CURRENT_ROUTE_SEGMENT_TRAFFIC_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentRouteSegmentTrafficVersion().hashCode();
    }
    if (hasRemainingWaypointsRouteVersion()) {
      hash = (37 * hash) + REMAINING_WAYPOINTS_ROUTE_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getRemainingWaypointsRouteVersion().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static google.maps.fleetengine.v1.GetTripRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(google.maps.fleetengine.v1.GetTripRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * GetTrip request message.
   * </pre>
   *
   * Protobuf type {@code maps.fleetengine.v1.GetTripRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:maps.fleetengine.v1.GetTripRequest)
      google.maps.fleetengine.v1.GetTripRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return google.maps.fleetengine.v1.TripApi
          .internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.maps.fleetengine.v1.TripApi
          .internal_static_maps_fleetengine_v1_GetTripRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              google.maps.fleetengine.v1.GetTripRequest.class,
              google.maps.fleetengine.v1.GetTripRequest.Builder.class);
    }

    // Construct using google.maps.fleetengine.v1.GetTripRequest.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      name_ = "";
      view_ = 0;
      currentRouteSegmentVersion_ = null;
      if (currentRouteSegmentVersionBuilder_ != null) {
        currentRouteSegmentVersionBuilder_.dispose();
        currentRouteSegmentVersionBuilder_ = null;
      }
      remainingWaypointsVersion_ = null;
      if (remainingWaypointsVersionBuilder_ != null) {
        remainingWaypointsVersionBuilder_.dispose();
        remainingWaypointsVersionBuilder_ = null;
      }
      routeFormatType_ = 0;
      currentRouteSegmentTrafficVersion_ = null;
      if (currentRouteSegmentTrafficVersionBuilder_ != null) {
        currentRouteSegmentTrafficVersionBuilder_.dispose();
        currentRouteSegmentTrafficVersionBuilder_ = null;
      }
      remainingWaypointsRouteVersion_ = null;
      if (remainingWaypointsRouteVersionBuilder_ != null) {
        remainingWaypointsRouteVersionBuilder_.dispose();
        remainingWaypointsRouteVersionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return google.maps.fleetengine.v1.TripApi
          .internal_static_maps_fleetengine_v1_GetTripRequest_descriptor;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest getDefaultInstanceForType() {
      return google.maps.fleetengine.v1.GetTripRequest.getDefaultInstance();
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest build() {
      google.maps.fleetengine.v1.GetTripRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public google.maps.fleetengine.v1.GetTripRequest buildPartial() {
      google.maps.fleetengine.v1.GetTripRequest result =
          new google.maps.fleetengine.v1.GetTripRequest(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(google.maps.fleetengine.v1.GetTripRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null ? header_ : headerBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.view_ = view_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.currentRouteSegmentVersion_ =
            currentRouteSegmentVersionBuilder_ == null
                ? currentRouteSegmentVersion_
                : currentRouteSegmentVersionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.remainingWaypointsVersion_ =
            remainingWaypointsVersionBuilder_ == null
                ? remainingWaypointsVersion_
                : remainingWaypointsVersionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.routeFormatType_ = routeFormatType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.currentRouteSegmentTrafficVersion_ =
            currentRouteSegmentTrafficVersionBuilder_ == null
                ? currentRouteSegmentTrafficVersion_
                : currentRouteSegmentTrafficVersionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.remainingWaypointsRouteVersion_ =
            remainingWaypointsRouteVersionBuilder_ == null
                ? remainingWaypointsRouteVersion_
                : remainingWaypointsRouteVersionBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof google.maps.fleetengine.v1.GetTripRequest) {
        return mergeFrom((google.maps.fleetengine.v1.GetTripRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(google.maps.fleetengine.v1.GetTripRequest other) {
      if (other == google.maps.fleetengine.v1.GetTripRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.view_ != 0) {
        setViewValue(other.getViewValue());
      }
      if (other.hasCurrentRouteSegmentVersion()) {
        mergeCurrentRouteSegmentVersion(other.getCurrentRouteSegmentVersion());
      }
      if (other.hasRemainingWaypointsVersion()) {
        mergeRemainingWaypointsVersion(other.getRemainingWaypointsVersion());
      }
      if (other.routeFormatType_ != 0) {
        setRouteFormatTypeValue(other.getRouteFormatTypeValue());
      }
      if (other.hasCurrentRouteSegmentTrafficVersion()) {
        mergeCurrentRouteSegmentTrafficVersion(other.getCurrentRouteSegmentTrafficVersion());
      }
      if (other.hasRemainingWaypointsRouteVersion()) {
        mergeRemainingWaypointsRouteVersion(other.getRemainingWaypointsRouteVersion());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getHeaderFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 26:
              {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
            case 50:
              {
                input.readMessage(
                    getCurrentRouteSegmentVersionFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 50
            case 58:
              {
                input.readMessage(
                    getRemainingWaypointsVersionFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 58
            case 64:
              {
                routeFormatType_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 64
            case 74:
              {
                input.readMessage(
                    getCurrentRouteSegmentTrafficVersionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000040;
                break;
              } // case 74
            case 82:
              {
                input.readMessage(
                    getRemainingWaypointsRouteVersionFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000080;
                break;
              } // case 82
            case 88:
              {
                view_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 88
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private google.maps.fleetengine.v1.RequestHeader header_;
    private com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.RequestHeader,
            google.maps.fleetengine.v1.RequestHeader.Builder,
            google.maps.fleetengine.v1.RequestHeaderOrBuilder>
        headerBuilder_;
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     *
     * @return The header.
     */
    public google.maps.fleetengine.v1.RequestHeader getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null
            ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()
            : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder setHeader(google.maps.fleetengine.v1.RequestHeader.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder mergeHeader(google.maps.fleetengine.v1.RequestHeader value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && header_ != null
            && header_ != google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeader.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    public google.maps.fleetengine.v1.RequestHeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null
            ? google.maps.fleetengine.v1.RequestHeader.getDefaultInstance()
            : header_;
      }
    }
    /**
     *
     *
     * <pre>
     * The standard Fleet Engine request header.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.RequestHeader header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            google.maps.fleetengine.v1.RequestHeader,
            google.maps.fleetengine.v1.RequestHeader.Builder,
            google.maps.fleetengine.v1.RequestHeaderOrBuilder>
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                google.maps.fleetengine.v1.RequestHeader,
                google.maps.fleetengine.v1.RequestHeader.Builder,
                google.maps.fleetengine.v1.RequestHeaderOrBuilder>(
                getHeader(), getParentForChildren(), isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     *
     *
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>
     * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>
     * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>
     * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>
     * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Must be in the format `providers/{provider}/trips/{trip}`.
     * The provider must be the Project ID (for example, `sample-cloud-project`)
     * of the Google Cloud Project of which the service account making
     * this call is a member.
     * </pre>
     *
     * <code>
     * string name = 3 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int view_ = 0;
    /**
     *
     *
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     *
     * @return The enum numeric value on the wire for view.
     */
    @java.lang.Override
    public int getViewValue() {
      return view_;
    }
    /**
     *
     *
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     *
     * @param value The enum numeric value on the wire for view to set.
     * @return This builder for chaining.
     */
    public Builder setViewValue(int value) {
      view_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     *
     * @return The view.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.TripView getView() {
      google.maps.fleetengine.v1.TripView result =
          google.maps.fleetengine.v1.TripView.forNumber(view_);
      return result == null ? google.maps.fleetengine.v1.TripView.UNRECOGNIZED : result;
    }
    /**
     *
     *
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     *
     * @param value The view to set.
     * @return This builder for chaining.
     */
    public Builder setView(google.maps.fleetengine.v1.TripView value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      view_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The subset of Trip fields that should be returned and their interpretation.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.TripView view = 11;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearView() {
      bitField0_ = (bitField0_ & ~0x00000004);
      view_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentRouteSegmentVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        currentRouteSegmentVersionBuilder_;
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     *
     * @return Whether the currentRouteSegmentVersion field is set.
     */
    public boolean hasCurrentRouteSegmentVersion() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     *
     * @return The currentRouteSegmentVersion.
     */
    public com.google.protobuf.Timestamp getCurrentRouteSegmentVersion() {
      if (currentRouteSegmentVersionBuilder_ == null) {
        return currentRouteSegmentVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : currentRouteSegmentVersion_;
      } else {
        return currentRouteSegmentVersionBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder setCurrentRouteSegmentVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRouteSegmentVersion_ = value;
      } else {
        currentRouteSegmentVersionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder setCurrentRouteSegmentVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersion_ = builderForValue.build();
      } else {
        currentRouteSegmentVersionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder mergeCurrentRouteSegmentVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentVersionBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)
            && currentRouteSegmentVersion_ != null
            && currentRouteSegmentVersion_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCurrentRouteSegmentVersionBuilder().mergeFrom(value);
        } else {
          currentRouteSegmentVersion_ = value;
        }
      } else {
        currentRouteSegmentVersionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public Builder clearCurrentRouteSegmentVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      currentRouteSegmentVersion_ = null;
      if (currentRouteSegmentVersionBuilder_ != null) {
        currentRouteSegmentVersionBuilder_.dispose();
        currentRouteSegmentVersionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentRouteSegmentVersionBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getCurrentRouteSegmentVersionFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentVersionOrBuilder() {
      if (currentRouteSegmentVersionBuilder_ != null) {
        return currentRouteSegmentVersionBuilder_.getMessageOrBuilder();
      } else {
        return currentRouteSegmentVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : currentRouteSegmentVersion_;
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which `Trip.route` or
     * `Trip.current_route_segment` data are retrieved. If route data are
     * unchanged since this timestamp, the route field is not set in the response.
     * If a minimum is unspecified, the route data are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_version = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getCurrentRouteSegmentVersionFieldBuilder() {
      if (currentRouteSegmentVersionBuilder_ == null) {
        currentRouteSegmentVersionBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getCurrentRouteSegmentVersion(), getParentForChildren(), isClean());
        currentRouteSegmentVersion_ = null;
      }
      return currentRouteSegmentVersionBuilder_;
    }

    private com.google.protobuf.Timestamp remainingWaypointsVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        remainingWaypointsVersionBuilder_;
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     *
     * @return Whether the remainingWaypointsVersion field is set.
     */
    public boolean hasRemainingWaypointsVersion() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     *
     * @return The remainingWaypointsVersion.
     */
    public com.google.protobuf.Timestamp getRemainingWaypointsVersion() {
      if (remainingWaypointsVersionBuilder_ == null) {
        return remainingWaypointsVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : remainingWaypointsVersion_;
      } else {
        return remainingWaypointsVersionBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder setRemainingWaypointsVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        remainingWaypointsVersion_ = value;
      } else {
        remainingWaypointsVersionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder setRemainingWaypointsVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersion_ = builderForValue.build();
      } else {
        remainingWaypointsVersionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder mergeRemainingWaypointsVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsVersionBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)
            && remainingWaypointsVersion_ != null
            && remainingWaypointsVersion_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRemainingWaypointsVersionBuilder().mergeFrom(value);
        } else {
          remainingWaypointsVersion_ = value;
        }
      } else {
        remainingWaypointsVersionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public Builder clearRemainingWaypointsVersion() {
      bitField0_ = (bitField0_ & ~0x00000010);
      remainingWaypointsVersion_ = null;
      if (remainingWaypointsVersionBuilder_ != null) {
        remainingWaypointsVersionBuilder_.dispose();
        remainingWaypointsVersionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRemainingWaypointsVersionBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getRemainingWaypointsVersionFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsVersionOrBuilder() {
      if (remainingWaypointsVersionBuilder_ != null) {
        return remainingWaypointsVersionBuilder_.getMessageOrBuilder();
      } else {
        return remainingWaypointsVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : remainingWaypointsVersion_;
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints` are retrieved. If they are unchanged since this
     * timestamp, the `remaining_waypoints` are not set in the response. If this
     * field is unspecified, `remaining_waypoints` is always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_version = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getRemainingWaypointsVersionFieldBuilder() {
      if (remainingWaypointsVersionBuilder_ == null) {
        remainingWaypointsVersionBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getRemainingWaypointsVersion(), getParentForChildren(), isClean());
        remainingWaypointsVersion_ = null;
      }
      return remainingWaypointsVersionBuilder_;
    }

    private int routeFormatType_ = 0;
    /**
     *
     *
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     *
     * @return The enum numeric value on the wire for routeFormatType.
     */
    @java.lang.Override
    public int getRouteFormatTypeValue() {
      return routeFormatType_;
    }
    /**
     *
     *
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     *
     * @param value The enum numeric value on the wire for routeFormatType to set.
     * @return This builder for chaining.
     */
    public Builder setRouteFormatTypeValue(int value) {
      routeFormatType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     *
     * @return The routeFormatType.
     */
    @java.lang.Override
    public google.maps.fleetengine.v1.PolylineFormatType getRouteFormatType() {
      google.maps.fleetengine.v1.PolylineFormatType result =
          google.maps.fleetengine.v1.PolylineFormatType.forNumber(routeFormatType_);
      return result == null ? google.maps.fleetengine.v1.PolylineFormatType.UNRECOGNIZED : result;
    }
    /**
     *
     *
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     *
     * @param value The routeFormatType to set.
     * @return This builder for chaining.
     */
    public Builder setRouteFormatType(google.maps.fleetengine.v1.PolylineFormatType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      routeFormatType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The returned current route format, `LAT_LNG_LIST_TYPE` (in `Trip.route`),
     * or `ENCODED_POLYLINE_TYPE` (in `Trip.current_route_segment`). The default
     * is `LAT_LNG_LIST_TYPE`.
     * </pre>
     *
     * <code>.maps.fleetengine.v1.PolylineFormatType route_format_type = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRouteFormatType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      routeFormatType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentRouteSegmentTrafficVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        currentRouteSegmentTrafficVersionBuilder_;
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     *
     * @return Whether the currentRouteSegmentTrafficVersion field is set.
     */
    public boolean hasCurrentRouteSegmentTrafficVersion() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     *
     * @return The currentRouteSegmentTrafficVersion.
     */
    public com.google.protobuf.Timestamp getCurrentRouteSegmentTrafficVersion() {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        return currentRouteSegmentTrafficVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : currentRouteSegmentTrafficVersion_;
      } else {
        return currentRouteSegmentTrafficVersionBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder setCurrentRouteSegmentTrafficVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentRouteSegmentTrafficVersion_ = value;
      } else {
        currentRouteSegmentTrafficVersionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder setCurrentRouteSegmentTrafficVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersion_ = builderForValue.build();
      } else {
        currentRouteSegmentTrafficVersionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder mergeCurrentRouteSegmentTrafficVersion(com.google.protobuf.Timestamp value) {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)
            && currentRouteSegmentTrafficVersion_ != null
            && currentRouteSegmentTrafficVersion_
                != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCurrentRouteSegmentTrafficVersionBuilder().mergeFrom(value);
        } else {
          currentRouteSegmentTrafficVersion_ = value;
        }
      } else {
        currentRouteSegmentTrafficVersionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public Builder clearCurrentRouteSegmentTrafficVersion() {
      bitField0_ = (bitField0_ & ~0x00000040);
      currentRouteSegmentTrafficVersion_ = null;
      if (currentRouteSegmentTrafficVersionBuilder_ != null) {
        currentRouteSegmentTrafficVersionBuilder_.dispose();
        currentRouteSegmentTrafficVersionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentRouteSegmentTrafficVersionBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getCurrentRouteSegmentTrafficVersionFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentRouteSegmentTrafficVersionOrBuilder() {
      if (currentRouteSegmentTrafficVersionBuilder_ != null) {
        return currentRouteSegmentTrafficVersionBuilder_.getMessageOrBuilder();
      } else {
        return currentRouteSegmentTrafficVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : currentRouteSegmentTrafficVersion_;
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.current_route_segment_traffic` is retrieved. If traffic data are
     * unchanged since this timestamp, the `current_route_segment_traffic` field
     * is not set in the response. If a minimum is unspecified, the traffic data
     * are always retrieved. Note that traffic is only available for On-Demand
     * Rides and Deliveries Solution customers.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp current_route_segment_traffic_version = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getCurrentRouteSegmentTrafficVersionFieldBuilder() {
      if (currentRouteSegmentTrafficVersionBuilder_ == null) {
        currentRouteSegmentTrafficVersionBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getCurrentRouteSegmentTrafficVersion(), getParentForChildren(), isClean());
        currentRouteSegmentTrafficVersion_ = null;
      }
      return currentRouteSegmentTrafficVersionBuilder_;
    }

    private com.google.protobuf.Timestamp remainingWaypointsRouteVersion_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        remainingWaypointsRouteVersionBuilder_;
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     *
     * @return Whether the remainingWaypointsRouteVersion field is set.
     */
    public boolean hasRemainingWaypointsRouteVersion() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     *
     * @return The remainingWaypointsRouteVersion.
     */
    public com.google.protobuf.Timestamp getRemainingWaypointsRouteVersion() {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        return remainingWaypointsRouteVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : remainingWaypointsRouteVersion_;
      } else {
        return remainingWaypointsRouteVersionBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder setRemainingWaypointsRouteVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        remainingWaypointsRouteVersion_ = value;
      } else {
        remainingWaypointsRouteVersionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder setRemainingWaypointsRouteVersion(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersion_ = builderForValue.build();
      } else {
        remainingWaypointsRouteVersionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder mergeRemainingWaypointsRouteVersion(com.google.protobuf.Timestamp value) {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)
            && remainingWaypointsRouteVersion_ != null
            && remainingWaypointsRouteVersion_
                != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRemainingWaypointsRouteVersionBuilder().mergeFrom(value);
        } else {
          remainingWaypointsRouteVersion_ = value;
        }
      } else {
        remainingWaypointsRouteVersionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public Builder clearRemainingWaypointsRouteVersion() {
      bitField0_ = (bitField0_ & ~0x00000080);
      remainingWaypointsRouteVersion_ = null;
      if (remainingWaypointsRouteVersionBuilder_ != null) {
        remainingWaypointsRouteVersionBuilder_.dispose();
        remainingWaypointsRouteVersionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRemainingWaypointsRouteVersionBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getRemainingWaypointsRouteVersionFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRemainingWaypointsRouteVersionOrBuilder() {
      if (remainingWaypointsRouteVersionBuilder_ != null) {
        return remainingWaypointsRouteVersionBuilder_.getMessageOrBuilder();
      } else {
        return remainingWaypointsRouteVersion_ == null
            ? com.google.protobuf.Timestamp.getDefaultInstance()
            : remainingWaypointsRouteVersion_;
      }
    }
    /**
     *
     *
     * <pre>
     * Indicates the minimum timestamp (exclusive) for which
     * `Trip.remaining_waypoints.traffic_to_waypoint` and
     * `Trip.remaining_waypoints.path_to_waypoint` data are retrieved. If data are
     * unchanged since this timestamp, the fields above are
     * not set in the response. If `remaining_waypoints_route_version` is
     * unspecified, traffic and path are always retrieved.
     * </pre>
     *
     * <code>.google.protobuf.Timestamp remaining_waypoints_route_version = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        getRemainingWaypointsRouteVersionFieldBuilder() {
      if (remainingWaypointsRouteVersionBuilder_ == null) {
        remainingWaypointsRouteVersionBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getRemainingWaypointsRouteVersion(), getParentForChildren(), isClean());
        remainingWaypointsRouteVersion_ = null;
      }
      return remainingWaypointsRouteVersionBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:maps.fleetengine.v1.GetTripRequest)
  }

  // @@protoc_insertion_point(class_scope:maps.fleetengine.v1.GetTripRequest)
  private static final google.maps.fleetengine.v1.GetTripRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new google.maps.fleetengine.v1.GetTripRequest();
  }

  public static google.maps.fleetengine.v1.GetTripRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTripRequest> PARSER =
      new com.google.protobuf.AbstractParser<GetTripRequest>() {
        @java.lang.Override
        public GetTripRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<GetTripRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTripRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public google.maps.fleetengine.v1.GetTripRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
