# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- "/java-secretmanager/samples/snippets/generated"
- "/java-secretmanager/grpc-google-.*/src"
- "/java-secretmanager/proto-google-.*/src"
- "/java-secretmanager/google-.*/src"

deep-preserve-regex:
- "/java-secretmanager/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/java-secretmanager/proto-google-cloud-secretmanager-v1beta1"
- "/java-secretmanager/grpc-google-cloud-secretmanager-v1beta1"
- "/java-secretmanager/google-cloud-secretmanager/src/main/java/com/google/cloud/secretmanager/v1beta1"
- "/java-secretmanager/google-cloud-secretmanager/src/test/java/com/google/cloud/secretmanager/v1beta1"
- "/java-secretmanager/proto-google-cloud-secretmanager-v1/src/main/java/com/google/cloud/secretmanager/v1/TopicName.java"
- "/java-secretmanager/google-.*/src/main/resources/META-INF/native-image/.*"
- "/java-secretmanager/google-.*/src/test/resources/META-INF/native-image/.*"

deep-copy-regex:
- source: "/google/cloud/secretmanager/(v\\d)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-secretmanager/$1/proto-google-cloud-secretmanager-$1/src"
- source: "/google/cloud/secretmanager/(v\\d)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-secretmanager/$1/grpc-google-cloud-secretmanager-$1/src"
- source: "/google/cloud/secretmanager/(v\\d)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-secretmanager/$1/google-cloud-secretmanager/src"
- source: "/google/cloud/secretmanager/(v\\d)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-secretmanager/$1/samples/snippets/generated"

api-name: "secretmanager"
