# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- "/java-retail/samples/snippets/generated"
- "/java-retail/grpc-google-.*/src"
- "/java-retail/proto-google-.*/src"
- "/java-retail/google-.*/src"

deep-preserve-regex:
- "/java-retail/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/java-retail/google-.*/src/main/resources/META-INF/native-image/.*"
- "/java-retail/google-.*/src/test/resources/META-INF/native-image/.*"

deep-copy-regex:
- source: "/google/cloud/retail/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-retail/$1/proto-google-cloud-retail-$1/src"
- source: "/google/cloud/retail/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-retail/$1/grpc-google-cloud-retail-$1/src"
- source: "/google/cloud/retail/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-retail/$1/google-cloud-retail/src"
- source: "/google/cloud/retail/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-retail/$1/samples/snippets/generated"

api-name: "retail"
