/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/discoveryengine/v1beta/license_config.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.discoveryengine.v1beta;

@com.google.protobuf.Generated
public interface LicenseConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.discoveryengine.v1beta.LicenseConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Immutable. Identifier. The fully qualified resource name of the license
   * config. Format:
   * `projects/{project}/locations/{location}/licenseConfigs/{license_config}`
   * </pre>
   *
   * <code>
   * string name = 1 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = IDENTIFIER];
   * </code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   *
   *
   * <pre>
   * Immutable. Identifier. The fully qualified resource name of the license
   * config. Format:
   * `projects/{project}/locations/{location}/licenseConfigs/{license_config}`
   * </pre>
   *
   * <code>
   * string name = 1 [(.google.api.field_behavior) = IMMUTABLE, (.google.api.field_behavior) = IDENTIFIER];
   * </code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * Required. Number of licenses purchased.
   * </pre>
   *
   * <code>int64 license_count = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The licenseCount.
   */
  long getLicenseCount();

  /**
   *
   *
   * <pre>
   * Required. Subscription tier information for the license config.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.SubscriptionTier subscription_tier = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The enum numeric value on the wire for subscriptionTier.
   */
  int getSubscriptionTierValue();

  /**
   *
   *
   * <pre>
   * Required. Subscription tier information for the license config.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.SubscriptionTier subscription_tier = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The subscriptionTier.
   */
  com.google.cloud.discoveryengine.v1beta.SubscriptionTier getSubscriptionTier();

  /**
   *
   *
   * <pre>
   * Output only. The state of the license config.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.LicenseConfig.State state = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   *
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();

  /**
   *
   *
   * <pre>
   * Output only. The state of the license config.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.LicenseConfig.State state = 4 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   *
   * @return The state.
   */
  com.google.cloud.discoveryengine.v1beta.LicenseConfig.State getState();

  /**
   *
   *
   * <pre>
   * Optional. Whether the license config should be auto renewed when it reaches
   * the end date.
   * </pre>
   *
   * <code>bool auto_renew = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The autoRenew.
   */
  boolean getAutoRenew();

  /**
   *
   *
   * <pre>
   * Required. The start date.
   * </pre>
   *
   * <code>.google.type.Date start_date = 6 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();

  /**
   *
   *
   * <pre>
   * Required. The start date.
   * </pre>
   *
   * <code>.google.type.Date start_date = 6 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The startDate.
   */
  com.google.type.Date getStartDate();

  /**
   *
   *
   * <pre>
   * Required. The start date.
   * </pre>
   *
   * <code>.google.type.Date start_date = 6 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.type.DateOrBuilder getStartDateOrBuilder();

  /**
   *
   *
   * <pre>
   * Optional. The planed end date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return Whether the endDate field is set.
   */
  boolean hasEndDate();

  /**
   *
   *
   * <pre>
   * Optional. The planed end date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The endDate.
   */
  com.google.type.Date getEndDate();

  /**
   *
   *
   * <pre>
   * Optional. The planed end date.
   * </pre>
   *
   * <code>.google.type.Date end_date = 7 [(.google.api.field_behavior) = OPTIONAL];</code>
   */
  com.google.type.DateOrBuilder getEndDateOrBuilder();

  /**
   *
   *
   * <pre>
   * Required. Subscription term.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.SubscriptionTerm subscription_term = 8 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The enum numeric value on the wire for subscriptionTerm.
   */
  int getSubscriptionTermValue();

  /**
   *
   *
   * <pre>
   * Required. Subscription term.
   * </pre>
   *
   * <code>
   * .google.cloud.discoveryengine.v1beta.SubscriptionTerm subscription_term = 8 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The subscriptionTerm.
   */
  com.google.cloud.discoveryengine.v1beta.SubscriptionTerm getSubscriptionTerm();

  /**
   *
   *
   * <pre>
   * Optional. Whether the license config is for free trial.
   * </pre>
   *
   * <code>bool free_trial = 9 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The freeTrial.
   */
  boolean getFreeTrial();

  /**
   *
   *
   * <pre>
   * Output only. Whether the license config is for Gemini bundle.
   * </pre>
   *
   * <code>bool gemini_bundle = 11 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The geminiBundle.
   */
  boolean getGeminiBundle();

  /**
   *
   *
   * <pre>
   * Output only. Indication of whether the subscription is terminated earlier
   * than the expiration date. This is usually terminated by pipeline once the
   * subscription gets terminated from subsv3.
   * </pre>
   *
   * <code>bool early_terminated = 12 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The earlyTerminated.
   */
  boolean getEarlyTerminated();

  /**
   *
   *
   * <pre>
   * Output only. The date when the subscription is terminated earlier than the
   * expiration date.
   * </pre>
   *
   * <code>
   * .google.type.Date early_termination_date = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   *
   * @return Whether the earlyTerminationDate field is set.
   */
  boolean hasEarlyTerminationDate();

  /**
   *
   *
   * <pre>
   * Output only. The date when the subscription is terminated earlier than the
   * expiration date.
   * </pre>
   *
   * <code>
   * .google.type.Date early_termination_date = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   *
   * @return The earlyTerminationDate.
   */
  com.google.type.Date getEarlyTerminationDate();

  /**
   *
   *
   * <pre>
   * Output only. The date when the subscription is terminated earlier than the
   * expiration date.
   * </pre>
   *
   * <code>
   * .google.type.Date early_termination_date = 13 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  com.google.type.DateOrBuilder getEarlyTerminationDateOrBuilder();
}
