# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


deep-remove-regex:
- "/java-container/grpc-google-.*/src"
- "/java-container/proto-google-.*/src"
- "/java-container/google-.*/src"

deep-preserve-regex:
- "/java-container/google-cloud-container/src/main/java/com/google/cloud/container/v1/SampleApp.java"
- "/java-container/google-cloud-container/src/test/java/com/google/cloud/container/v1/it/ITSystemTest.java"
- "/java-container/google-cloud-container/src/test/java/com/google/cloud/container/v1/it/Util.java"

deep-copy-regex:
- source: "/google/container/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-container/$1/proto-google-cloud-container-$1/src"
- source: "/google/container/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-container/$1/grpc-google-cloud-container-$1/src"
- source: "/google/container/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-container/$1/google-cloud-container/src"

api-name: container
