# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- "/java-automl/samples/snippets/generated"
- "/java-automl/grpc-google-.*/src"
- "/java-automl/proto-google-.*/src"
- "/java-automl/google-.*/src"

deep-preserve-regex:
- "/java-automl/google-.*/src/main/resources/META-INF/native-image/.*"
- "/java-automl/google-.*/src/test/resources/META-INF/native-image/.*"

deep-copy-regex:
- source: "/google/cloud/automl/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-automl/$1/proto-google-cloud-automl-$1/src"
- source: "/google/cloud/automl/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-automl/$1/grpc-google-cloud-automl-$1/src"
- source: "/google/cloud/automl/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-automl/$1/google-cloud-automl/src"
- source: "/google/cloud/automl/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-automl/$1/samples/snippets/generated"

api-name: automl
