# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- "/java-dialogflow/samples/snippets/generated"
- "/java-dialogflow/grpc-google-.*/src"
- "/java-dialogflow/proto-google-.*/src"
- "/java-dialogflow/google-.*/src"

deep-preserve-regex:
- "/java-dialogflow/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"
- "/java-dialogflow/google-cloud-dialogflow/src/test/java/com/google/cloud/dialogflow/v2/ContextManagementSmokeTest.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ConversationModelName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2/src/main/java/com/google/cloud/dialogflow/v2/ProjectAgentName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ConversationModelName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EnvironmentContextName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EnvironmentSessionEntityTypeName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/EnvironmentSessionName.java"
- "/java-dialogflow/proto-google-cloud-dialogflow-v2beta1/src/main/java/com/google/cloud/dialogflow/v2beta1/ProjectAgentName.java"
- "/java-dialogflow/google-.*/src/main/resources/META-INF/native-image/*"
- "/java-dialogflow/google-.*/src/test/resources/META-INF/native-image/*"
- "/java-dialogflow/google-.*/src/main/resources/META-INF/native-image/.*"
- "/java-dialogflow/google-.*/src/test/resources/META-INF/native-image/.*"

deep-copy-regex:
- dest: "/owl-bot-staging/java-dialogflow/$1/proto-google-cloud-dialogflow-$1/src"
  source: "/google/cloud/dialogflow/(v.*)/.*-java/proto-google-.*/src"
- dest: "/owl-bot-staging/java-dialogflow/$1/grpc-google-cloud-dialogflow-$1/src"
  source: "/google/cloud/dialogflow/(v.*)/.*-java/grpc-google-.*/src"
- dest: "/owl-bot-staging/java-dialogflow/$1/google-cloud-dialogflow/src"
  source: "/google/cloud/dialogflow/(v.*)/.*-java/gapic-google-.*/src"
- dest: "/owl-bot-staging/java-dialogflow/$1/samples/snippets/generated"
  source: "/google/cloud/dialogflow/(v.*)/.*-java/samples/snippets/generated"
