custom_content: |
### Client Library Usage Examples

[Cleint library examples](https://developers.google.com/maps/documentation/places/web-service/client-library-examples#java) of how to use the Places API (New) are available to help you get started.
