# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- /java-pubsub/grpc-google-.*/src
- /java-pubsub/proto-google-.*/src
- /java-pubsub/google-.*/src
deep-preserve-regex:
- /java-pubsub/.*google-.*/src/main/java/.*/stub/Version.java
- /java-pubsub/google-cloud-pubsub/src/test/resources/META-INF/native-image/.*
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/.*/v.*/it/IT.*Test.java
- /java-pubsub/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/DeletedTopic.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectSnapshotName.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectSubscriptionName.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/ProjectTopicName.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/TopicNames.java
- /java-pubsub/proto-google-cloud-pubsub-v1/src/main/java/com/google/pubsub/v1/UntypedTopicName.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/it/ITPubSubTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/CustomArgumentMatchers.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeClock.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakePublisherServiceImpl.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeScheduledExecutorService.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/FakeSubscriberServiceImpl.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDataMatcher.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/MessageDispatcherTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenCensusUtilTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/OpenTelemetryTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/PublisherImplTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SequentialExecutorServiceTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StatusUtilTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnectionTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberShutdownSettingsTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/SubscriberTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/TopicAdminSmokeTest.java
- /java-pubsub/google-cloud-pubsub/src/test/java/com/google/cloud/pubsub/v1/WaiterTest.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumer.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerImpl.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerWithResponse.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckReplyConsumerWithResponseImpl.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckRequestData.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/AckResponse.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageReceiver.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageReceiverWithAckResponse.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/ModackRequestData.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/OpenCensusUtil.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/OpenTelemetryPubsubTracer.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PublisherInterface.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/PubsubMessageWrapper.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SequentialExecutorService.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StatusUtil.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/StreamingSubscriberConnection.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriberInterface.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriberShutdownSettings.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/SubscriberStats.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Waiter.java
- /java-pubsub/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/LoggingUtil.java
deep-copy-regex:
- source: /google/pubsub/(v.*)/.*-java/proto-google-.*/src
  dest: /owl-bot-staging/java-pubsub/$1/proto-google-cloud-pubsub-$1/src
- source: /google/pubsub/(v.*)/.*-java/grpc-google-.*/src
  dest: /owl-bot-staging/java-pubsub/$1/grpc-google-cloud-pubsub-$1/src
- source: /google/pubsub/(v.*)/.*-java/gapic-google-.*/src
  dest: /owl-bot-staging/java-pubsub/$1/google-cloud-pubsub/src
