permissions:
  contents: read

name: CHANGELOG.md generation test

on:
  pull_request:
    branches: [ main ]
    paths:
    - .github/release-note-generation/**

jobs:
  changelog-generation-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        persist-credentials: false
    - name: Unit Test
      run: |
        python3 .github/release-note-generation/unit_test.py
    - name: Golden Test
      run: |
        sh .github/release-note-generation/golden_test.sh
