# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Github action job to test core java library features on
# downstream client libraries before they are released.
on:
  push:
    branches:
    - main
  pull_request:
name: ci
jobs:
  # detect whether or note we should run "bulk" (non-handwritten) unit tests
  bulk-filter:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
      ci: ${{ steps.filter.outputs.ci }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          src:
            - '!(java-bigquery|java-bigquerystorage|java-datastore|java-logging-logback|java-logging|java-spanner|java-storage|google-auth-library-java)/**/*.java'
            - '!(java-bigquery|java-bigquerystorage|java-datastore|java-logging-logback|java-logging|java-spanner|java-storage|google-auth-library-java)/**/pom.xml'
            - 'pom.xml'
          ci:
            - '.github/workflows/ci.yaml'
            - '.kokoro/**'
  # these unit tests are "bulk" (non-handwritten) libraries
  units:
    runs-on: ubuntu-latest
    needs: bulk-filter
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17, 21, 25]
    steps:
    - name: Get current week within the year
      id: date
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - run: java -version
    - uses: actions/cache@v4
      id: mvn-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
    - run: .kokoro/build.sh
      if: ${{ needs.bulk-filter.outputs.src == 'true' || needs.bulk-filter.outputs.ci == 'true' }}
      env:
        JOB_TYPE: test
        JOB_NAME: units-${{matrix.java}}
  units-8-runtime:
    runs-on: ubuntu-latest
    needs: bulk-filter
    name: "units (8)"
    steps:
    - name: Get current week within the year
      id: date
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - name: "Set jvm system property environment variable for surefire plugin (unit tests)"
      # Maven surefire plugin (unit tests) allows us to specify JVM to run the tests.
      # https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#jvm
      run: echo "SUREFIRE_JVM_OPT=-Djvm=${JAVA_HOME}/bin/java" >> $GITHUB_ENV
      shell: bash    
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
    - uses: actions/cache@v4
      id: mvn-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
    - run: .kokoro/build.sh
      if: ${{ needs.bulk-filter.outputs.src == 'true' || needs.bulk-filter.outputs.ci == 'true' }}
      shell: bash      
      env:
        JOB_TYPE: test
        JOB_NAME: units-8-runtime-${{matrix.java}}
  # detect which libraries have changed
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        # For each library, run CI in split repos where there are changes in:
        # 1. Changes inside the split repo's module
        # 2. Java code changes in upstream modules: Auth Library and Sdk-Platform-Java
        # 3. Upstream dependency version changes: Shared-Deps and Gapic-Generator-Pom-Parent
        filters: |
          google-auth-library-java:
            - 'google-auth-library-java/**'
          java-bigquery:
            - 'java-bigquery/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-bigquerystorage:
            - 'java-bigquerystorage/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-datastore:
            - 'java-datastore/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-logging-logback:
            - 'java-logging-logback/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-logging:
            - 'java-logging/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-spanner:
            - 'java-spanner/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
          java-storage:
            - 'java-storage/**'
            - 'google-auth-library-java/**/*.java'
            - 'google-auth-library-java/**/pom.xml'
            - 'sdk-platform-java/**/*.java'
            - 'sdk-platform-java/java-shared-dependencies/**/pom.xml'
            - 'sdk-platform-java/gapic-generator-java-pom-parent/pom.xml'
  split-units:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        java: [11, 17, 21, 25]
    steps:
    - name: Get current week within the year
      id: date
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - run: .kokoro/build.sh
      env:
        BUILD_SUBDIR: ${{matrix.package}}
        JOB_TYPE: test
        JOB_NAME: units-${{matrix.package}}-${{matrix.java}}
  split-units-8:
    runs-on: ubuntu-latest
    name: "split-units"
    needs: changes
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
        java: [8]
    steps:
    - name: Get current week within the year
      id: date
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
    - run: java -version
    - uses: actions/cache@v4
      id: mvn-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.week_of_year }}
    - name: Install all modules using Java 11
      shell: bash
      run: .kokoro/build.sh
      env:
        BUILD_SUBDIR: ${{matrix.package}}
        JOB_TYPE: install
    - uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - run: java -version
    - name: Run tests in Java ${{matrix.java}} with the source compiled in Java 11
      run: |
        mvn test \
          -B -ntp \
          -Pquick-build \
          -Dorg.slf4j.simpleLogger.showDateTime=true \
          -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS \
          -Dmaven.wagon.http.retryHandler.count=5 \
          --also-make \
          -T 1C
      env:
        BUILD_SUBDIR: ${{matrix.package}}
        JOB_TYPE: test
        JOB_NAME: units-8-runtime-${{matrix.java}}
      working-directory: ${{matrix.package}}
  split-clirr:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - run: .kokoro/build.sh
      env:
        BUILD_SUBDIR: ${{matrix.package}}
        JOB_TYPE: clirr
        JOB_NAME: clirr-${{matrix.package}}
  split-dependencies:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: .kokoro/dependencies.sh
      env:
        BUILD_SUBDIR: ${{matrix.package}}
  required:
    needs: [ changes, split-units, split-clirr, split-dependencies ]
    name: conditional-required-check
    if: ${{ always() }} # Always run even if any "needs" jobs fail
    runs-on: ubuntu-22.04
    steps:
      - name: Fail if any previous failure
        if: ${{ needs.changes.outputs.packages != '[]' && contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Success otherwise
        run: echo "Success!"
  windows:
    runs-on: windows-latest
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: 'maven'
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: test
        JOB_NAME: windows-units
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: lint
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
  enforcer:
    runs-on: ubuntu-latest
    steps:
    - name: Get current week within the year
      id: date
      run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - run: java -version
    - name: Install Maven modules to local Maven repository
      run: .kokoro/build.sh
      env:
        JOB_TYPE: install
    - run: java -version
    - run: mvn -B -ntp enforcer:enforce@enforce -T 1C
  gapic-libraries-bom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: maven
    - name: Install Maven modules to local Maven repository
      run: .kokoro/build.sh
      env:
        JOB_TYPE: install
    - name: Validate gapic-libraries-bom
      uses: googleapis/java-cloud-bom/tests/validate-bom@v26.79.0
      with:
        bom-path: gapic-libraries-bom/pom.xml
  generation-config-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: validate generation configuration
      shell: bash
      run: |
        bash generation/run_generator_docker.sh "${library_generation_image_tag}" "${{ github.base_ref || 'main' }}" \
          -e GENERATOR_VERSION="${library_generation_image_tag}" \
          --quiet \
          -u "$(id -u):$(id -g)" \
          -v "$(pwd):${workspace_name}" \
          --entrypoint python \
          -- \
          /src/library_generation/cli/entry_point.py validate-generation-config
      env:
        library_generation_image_tag: 2.68.0
        workspace_name: /workspace
