permissions:
  contents: read

name: Create additional tags for each release

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Permission to create tag
      # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        token: ${{ secrets.CLOUD_JAVA_BOT_GITHUB_TOKEN }}
        persist-credentials: false
    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Create additional tags
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.CLOUD_JAVA_BOT_GITHUB_TOKEN }}
      run: |
        ARTIFACT_IDS=('google-cloud-shared-dependencies' 'api-common' 'gax' 'google-cloud-bigtable' 'libraries-bom')
        for ARTIFACT_ID in "${ARTIFACT_IDS[@]}"; do
          VERSION=$(grep "^${ARTIFACT_ID}:" versions.txt | cut -d':' -f2 | tr -d '[:space:]')
          TAG_NAME="${ARTIFACT_ID}/v$VERSION"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
            echo "Tag $TAG_NAME already exists on remote. Skipping."
            continue
          fi
          git tag $TAG_NAME
          git push origin $TAG_NAME
          if [ "${ARTIFACT_ID}" = "libraries-bom" ]; then
            echo "Creating GitHub Release for ${TAG_NAME}"
            gh release create "${TAG_NAME}" --title "GCP Libraries BOM ${VERSION}" --notes "libraries-bom release."
          fi
        done
