# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# GitHub action job to test core java library features on
# downstream client libraries before they are released.
on:
  push:
    branches:
    - main
  pull_request:
name: google-auth-library-java ci
env:
  BUILD_SUBDIR: google-auth-library-java
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      library: ${{ steps.filter.outputs.library }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          library:
            - 'google-auth-library-java/**'
            - '.github/workflows/google-auth-library-java-ci.yaml'
  units-logging:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17, 21, 25]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - run: java -version
    - run: .kokoro/build.sh
      env:
        BUILD_SUBDIR: google-auth-library-java
        JOB_TYPE: test
        SUREFIRE_JVM_OPT: "-P '!slf4j2x,slf4j2x-test'"
  clirr:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - run: java -version
    - run: .kokoro/build.sh
      env:
        JOB_TYPE: clirr
        BUILD_SUBDIR: google-auth-library-java
  dependencies:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - run: .kokoro/dependencies.sh

  required:
    needs: [ units-logging, clirr, dependencies ]
    name: conditional-required-check
    if: ${{ always() }} # Always run even if any "needs" jobs fail
    runs-on: ubuntu-22.04
    steps:
      - name: Fail if any previous failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Success otherwise
        run: echo "Success!"