on:
  pull_request:
name: java-firestore Unmanaged dependency check
env:
  BUILD_SUBDIR: java-firestore
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      library: ${{ steps.filter.outputs.library }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          library:
            - 'java-firestore/**'
  unmanaged_dependency_check:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Install modules
      shell: bash
      run: .kokoro/build.sh
    - name: Unmanaged dependency check
      uses: googleapis/google-cloud-java/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check@v1.85.0
      with:
        bom-path: google-cloud-firestore-bom/pom.xml
