permissions:
  contents: read

on:
  push:
    branches:
    - main
  pull_request:
name: java-spanner integration-tests-against-emulator
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      library: ${{ steps.filter.outputs.library }}
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          library:
            - 'java-spanner/**'
  units:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-latest

    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator@sha256:ad54472fe7b161b9214f7f816f304b649a4779e348229c375ac067f5ed5a6422 # 1.5.55
        ports:
          - 9010:9010
          - 9020:9020

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false
    - uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
      with:
        distribution: temurin
        java-version: 11
    - name: Running tests
      run: .kokoro/build.sh
      env:
        JOB_TYPE: test
        BUILD_SUBDIR: java-spanner
        SPANNER_EMULATOR_HOST: localhost:9010
        GOOGLE_CLOUD_PROJECT: emulator-test-project
        SUREFIRE_JVM_OPT: '-Penable-integration-tests -DskipUnitTests=true -Dspanner.testenv.instance="" -Dmaven.main.skip=true'
