permissions:
  contents: read

name: sdk-platform-java Run dependency analyzer
on:
  workflow_dispatch:
    inputs:
      system:
        description: the package management system
        required: true
        type: choice
        default: maven
        options:
        - maven
      name:
        description: the name of the dependency
        required: true
        type: string
      version:
        description: the version of the dependency
        required: true
        type: string
env:
  BUILD_SUBDIR: sdk-platform-java
jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      library: ${{ steps.filter.outputs.library }}
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
      id: filter
      with:
        filters: |
          library:
            - 'sdk-platform-java/**'
  Run-dependency-analyzer:
    needs: filter
    if: ${{ needs.filter.outputs.library == 'true' }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        persist-credentials: false
    - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.8.2
    - name: Install dependency analyzer
      shell: bash
      run: |
        mvn clean install -V --batch-mode --no-transfer-progress -DskipTests
      working-directory: java-shared-dependencies/dependency-analyzer
    - name: Check dependency information
      shell: bash
      run: |
        mvn exec:java -Ddep.system=${GITHUB_EVENT_INPUTS_SYSTEM} -Ddep.name=${GITHUB_EVENT_INPUTS_NAME} -Ddep.version=${GITHUB_EVENT_INPUTS_VERSION}
      working-directory: java-shared-dependencies/dependency-analyzer
      env:
        GITHUB_EVENT_INPUTS_SYSTEM: ${{ github.event.inputs.system }}
        GITHUB_EVENT_INPUTS_NAME: ${{ github.event.inputs.name }}
        GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
