permissions:
  contents: read

on:
  pull_request:
    # Runs on PRs targeting main, but will be filtered for Release PRs
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      protobuf_runtime_versions:
        description: 'Comma separated list of Protobuf-Java versions (i.e. "3.25.x","4.x.y"). Leave empty to use version from pom-parent.'
        required: false
  schedule:
    - cron: '0 1 * * *' # Nightly at 1am

# This job intends to test the compatibility of Protobuf runtime version against modules in the monorepo.
name: sdk-platform-java Downstream Protobuf Compatibility Check Nightly
jobs:
  setup:
    if: github.head_ref == 'release-please--branches--main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      protobuf-versions: ${{ steps.resolve-versions.outputs.protobuf-versions }}
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Use GCP Maven Mirror
        run: mkdir -p "${HOME}/.m2" && cp settings.xml "${HOME}/.m2"
      - id: resolve-versions
        name: Resolve Protobuf versions
        env:
          INPUT_VERSIONS: ${{ inputs.protobuf_runtime_versions }}
        run: |
          if [ -n "${INPUT_VERSIONS}" ]; then
            echo "protobuf-versions=[${INPUT_VERSIONS}]" >> "$GITHUB_OUTPUT"
          else
            VERSION=$(mvn -f sdk-platform-java/gapic-generator-java-pom-parent/pom.xml help:evaluate -Dexpression=protobuf.version -q -DforceStdout)
            echo "protobuf-versions=[\"${VERSION}\"]" >> "$GITHUB_OUTPUT"
          fi

  downstream-protobuf-test:
    needs: setup
    # This job runs if any of the three conditions match:
    # 1. PR is raised from Release-Please (PR comes from branch: release-please--branches-main)
    # 2. Job is invoked by the nightly job (scheduled event)
    # 3. Job is manually invoked via Github UI (workflow_dispatch event)
    if: github.head_ref == 'release-please--branches--main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        module:
          - java-bigtable
          - java-bigquery
          - java-bigquerystorage
          - java-datastore
          - java-firestore
          - java-grafeas
          - java-logging
          - java-logging-logback
          - java-pubsub
          - java-resourcemanager
          - java-showcase
          - java-spanner
          - java-spanner-jdbc
          - java-storage
          - java-storage-nio
          - java-translate
        protobuf-version: ${{ fromJSON(needs.setup.outputs.protobuf-versions) }}
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      # Java Client Libraries are compiled with Java 11 and target Java 8. Java 11 is required because GraalVM
      # minimum support is for Java 11.
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Install monorepo modules
        shell: bash
        run: .kokoro/build.sh
        env:
          BUILD_SUBDIR: ${{ matrix.module }}
          JOB_TYPE: install
      - name: Print Protobuf-Java testing version
        run: echo "Testing with Protobuf-Java v${PROTOBUF_RUNTIME_VERSION}"
        env:
          PROTOBUF_RUNTIME_VERSION: ${{ matrix.protobuf-version }}
      - name: Perform downstream source compatibility testing
        run: ./sdk-platform-java/.kokoro/nightly/downstream-protobuf-source-compatibility.sh
        env:
          MODULES_UNDER_TEST: ${{ matrix.module }}
          PROTOBUF_RUNTIME_VERSION: ${{ matrix.protobuf-version }}
          GOOGLE_CLOUD_PROJECT: placeholder-test-project
      - name: Perform downstream binary compatibility testing
        run: ./sdk-platform-java/.kokoro/nightly/downstream-protobuf-binary-compatibility.sh
        env:
          MODULES_UNDER_TEST: ${{ matrix.module }}
          PROTOBUF_RUNTIME_VERSION: ${{ matrix.protobuf-version }}
