permissions:
  contents: read

on:
  pull_request:
name: sdk-platform-java Unmanaged dependency check
jobs:
  unmanaged_dependency_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        persist-credentials: false
    - uses: actions/setup-java@e9fbacdec3bb3b6036605a3e6f7995d66773a8c6 # v3.14.2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - name: Install all modules first
      shell: bash
      run: .kokoro/build.sh
      env:
        JOB_TYPE: install
    - name: Unmanaged dependency check
      uses: ./sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check
      with:
        bom-path: gapic-libraries-bom/pom.xml
