permissions:
  contents: read

on:
  pull_request:

name: sdk-platform-java Unmanaged dependency check

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      run_check: ${{ steps.filter.outputs.run_check }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            run_check:
              - '**/pom.xml'
              - 'gapic-libraries-bom/**'
              - 'sdk-platform-java/java-shared-dependencies/**'
              - '.github/workflows/unmanaged_dependency_check.yaml'

  unmanaged_dependency_check:
    needs: filter
    if: ${{ needs.filter.outputs.run_check == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Use GCP Maven Mirror
        run: mkdir -p "${HOME}/.m2" && cp settings.xml "${HOME}/.m2"
      - name: Install all modules
        shell: bash
        run: |
          mvn install -Pquick-build -DskipTests -B -ntp -T 1C
      - name: Unmanaged dependency check
        uses: ./sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check
        with:
          bom-path: gapic-libraries-bom/pom.xml
