/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/ces/v1/agent_service.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.ces.v1;

@com.google.protobuf.Generated
public interface CreateExampleRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.ces.v1.CreateExampleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The resource name of the app to create an example in.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The parent.
   */
  java.lang.String getParent();

  /**
   *
   *
   * <pre>
   * Required. The resource name of the app to create an example in.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();

  /**
   *
   *
   * <pre>
   * Optional. The ID to use for the example, which will become the final
   * component of the example's resource name. If not provided, a unique ID will
   * be automatically assigned for the example.
   * </pre>
   *
   * <code>string example_id = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The exampleId.
   */
  java.lang.String getExampleId();

  /**
   *
   *
   * <pre>
   * Optional. The ID to use for the example, which will become the final
   * component of the example's resource name. If not provided, a unique ID will
   * be automatically assigned for the example.
   * </pre>
   *
   * <code>string example_id = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for exampleId.
   */
  com.google.protobuf.ByteString getExampleIdBytes();

  /**
   *
   *
   * <pre>
   * Required. The example to create.
   * </pre>
   *
   * <code>.google.cloud.ces.v1.Example example = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the example field is set.
   */
  boolean hasExample();

  /**
   *
   *
   * <pre>
   * Required. The example to create.
   * </pre>
   *
   * <code>.google.cloud.ces.v1.Example example = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The example.
   */
  com.google.cloud.ces.v1.Example getExample();

  /**
   *
   *
   * <pre>
   * Required. The example to create.
   * </pre>
   *
   * <code>.google.cloud.ces.v1.Example example = 3 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.ces.v1.ExampleOrBuilder getExampleOrBuilder();
}
